<?php
/**
 * Class ModelToolFontAwesome
 *
 * @package NivoCart
 */
class ModelToolFontAwesome extends Model {
	/**
	 * Functions Get
	 */
	public function getFonts(): array {
		$fonts = $this->cache->get('fonts');

		if (!$fonts) {
			$fonts = [];

			$fonts[] = ['class' => 'fa-glass','title' => 'Glass'];
			$fonts[] = ['class' => 'fa-music','title' => 'Music'];
			$fonts[] = ['class' => 'fa-search','title' => 'Search'];
			$fonts[] = ['class' => 'fa-envelope-o','title' => 'Envelope O'];
			$fonts[] = ['class' => 'fa-heart','title' => 'Heart'];
			$fonts[] = ['class' => 'fa-star','title' => 'Star'];
			$fonts[] = ['class' => 'fa-star-o','title' => 'Star O'];
			$fonts[] = ['class' => 'fa-user','title' => 'User'];
			$fonts[] = ['class' => 'fa-film','title' => 'Film'];
			$fonts[] = ['class' => 'fa-th-large','title' => 'Th Large'];
			$fonts[] = ['class' => 'fa-th','title' => 'Th'];
			$fonts[] = ['class' => 'fa-th-list','title' => 'Th List'];
			$fonts[] = ['class' => 'fa-check','title' => 'Check'];
			$fonts[] = ['class' => 'fa-remove','title' => 'Remove'];
			$fonts[] = ['class' => 'fa-close','title' => 'Close'];
			$fonts[] = ['class' => 'fa-times','title' => 'Times'];
			$fonts[] = ['class' => 'fa-search-plus','title' => 'Search Plus'];
			$fonts[] = ['class' => 'fa-search-minus','title' => 'Search Minus'];
			$fonts[] = ['class' => 'fa-power-off','title' => 'Power Off'];
			$fonts[] = ['class' => 'fa-signal','title' => 'Signal'];
			$fonts[] = ['class' => 'fa-gear','title' => 'Gear'];
			$fonts[] = ['class' => 'fa-cog','title' => 'Cog'];
			$fonts[] = ['class' => 'fa-trash','title' => 'Trash'];
			$fonts[] = ['class' => 'fa-home','title' => 'Home'];
			$fonts[] = ['class' => 'fa-file-o','title' => 'File O'];
			$fonts[] = ['class' => 'fa-clock-o','title' => 'Clock O'];
			$fonts[] = ['class' => 'fa-road','title' => 'Road'];
			$fonts[] = ['class' => 'fa-download','title' => 'Download'];
			$fonts[] = ['class' => 'fa-arrow-circle-o-down','title' => 'Arrow Circle O Down'];
			$fonts[] = ['class' => 'fa-arrow-circle-o-up','title' => 'Arrow Circle O Up'];
			$fonts[] = ['class' => 'fa-inbox','title' => 'Inbox'];
			$fonts[] = ['class' => 'fa-play-circle-o','title' => 'Play Circle O'];
			$fonts[] = ['class' => 'fa-rotate-right','title' => 'Rotate Right'];
			$fonts[] = ['class' => 'fa-repeat','title' => 'Repeat'];
			$fonts[] = ['class' => 'fa-refresh','title' => 'Refresh'];
			$fonts[] = ['class' => 'fa-list-alt','title' => 'List Alt'];
			$fonts[] = ['class' => 'fa-lock','title' => 'Lock'];
			$fonts[] = ['class' => 'fa-flag','title' => 'Flag'];
			$fonts[] = ['class' => 'fa-headphones','title' => 'Headphones'];
			$fonts[] = ['class' => 'fa-volume-off','title' => 'Volume Off'];
			$fonts[] = ['class' => 'fa-volume-down','title' => 'Volume Down'];
			$fonts[] = ['class' => 'fa-volume-up','title' => 'Volume Up'];
			$fonts[] = ['class' => 'fa-qrcode','title' => 'QR Code'];
			$fonts[] = ['class' => 'fa-barcode','title' => 'Barcode'];
			$fonts[] = ['class' => 'fa-tag','title' => 'Tag'];
			$fonts[] = ['class' => 'fa-tags','title' => 'Tags'];
			$fonts[] = ['class' => 'fa-book','title' => 'Book'];
			$fonts[] = ['class' => 'fa-bookmark','title' => 'Bookmark'];
			$fonts[] = ['class' => 'fa-print','title' => 'Print'];
			$fonts[] = ['class' => 'fa-camera','title' => 'Camera'];
			$fonts[] = ['class' => 'fa-font','title' => 'Font'];
			$fonts[] = ['class' => 'fa-bold','title' => 'Bold'];
			$fonts[] = ['class' => 'fa-italic','title' => 'Italic'];
			$fonts[] = ['class' => 'fa-text-height','title' => 'Text Height'];
			$fonts[] = ['class' => 'fa-text-width','title' => 'Text Width'];
			$fonts[] = ['class' => 'fa-align-left','title' => 'Align Left'];
			$fonts[] = ['class' => 'fa-align-center','title' => 'Align Center'];
			$fonts[] = ['class' => 'fa-align-right','title' => 'Align Right'];
			$fonts[] = ['class' => 'fa-align-justify','title' => 'Align Justify'];
			$fonts[] = ['class' => 'fa-list','title' => 'List'];
			$fonts[] = ['class' => 'fa-dedent','title' => 'Dedent'];
			$fonts[] = ['class' => 'fa-outdent','title' => 'Outdent'];
			$fonts[] = ['class' => 'fa-indent','title' => 'Indent'];
			$fonts[] = ['class' => 'fa-video-camera','title' => 'Video Camera'];
			$fonts[] = ['class' => 'fa-photo','title' => 'Photo'];
			$fonts[] = ['class' => 'fa-image','title' => 'Image'];
			$fonts[] = ['class' => 'fa-picture-o','title' => 'Picture O'];
			$fonts[] = ['class' => 'fa-pencil','title' => 'Pencil'];
			$fonts[] = ['class' => 'fa-map-marker','title' => 'Map Marker'];
			$fonts[] = ['class' => 'fa-adjust','title' => 'Adjust'];
			$fonts[] = ['class' => 'fa-tint','title' => 'Tint'];
			$fonts[] = ['class' => 'fa-edit','title' => 'Edit'];
			$fonts[] = ['class' => 'fa-pencil-square-o','title' => 'Pencil Square O'];
			$fonts[] = ['class' => 'fa-share-square-o','title' => 'Share Square O'];
			$fonts[] = ['class' => 'fa-check-square-o','title' => 'Check Square O'];
			$fonts[] = ['class' => 'fa-arrows','title' => 'Arrows'];
			$fonts[] = ['class' => 'fa-step-backward','title' => 'Step Backward'];
			$fonts[] = ['class' => 'fa-fast-backward','title' => 'Fast Backward'];
			$fonts[] = ['class' => 'fa-backward','title' => 'Backward'];
			$fonts[] = ['class' => 'fa-play','title' => 'Play'];
			$fonts[] = ['class' => 'fa-pause','title' => 'Pause'];
			$fonts[] = ['class' => 'fa-stop','title' => 'Stop'];
			$fonts[] = ['class' => 'fa-forward','title' => 'Forward'];
			$fonts[] = ['class' => 'fa-fast-forward','title' => 'Fast Forward'];
			$fonts[] = ['class' => 'fa-step-forward','title' => 'Step Forward'];
			$fonts[] = ['class' => 'fa-eject','title' => 'Eject'];
			$fonts[] = ['class' => 'fa-chevron-left','title' => 'Chevron Left'];
			$fonts[] = ['class' => 'fa-chevron-right','title' => 'Chevron Right'];
			$fonts[] = ['class' => 'fa-plus-circle','title' => 'Plus Circle'];
			$fonts[] = ['class' => 'fa-minus-circle','title' => 'Minus Circle'];
			$fonts[] = ['class' => 'fa-times-circle','title' => 'Times Circle'];
			$fonts[] = ['class' => 'fa-check-circle','title' => 'Check Circle'];
			$fonts[] = ['class' => 'fa-question-circle','title' => 'Question Circle'];
			$fonts[] = ['class' => 'fa-info-circle','title' => 'Info Circle'];
			$fonts[] = ['class' => 'fa-crosshairs','title' => 'Crosshairs'];
			$fonts[] = ['class' => 'fa-times-circle-o','title' => 'Times Circle O'];
			$fonts[] = ['class' => 'fa-check-circle-o','title' => 'Check Circle O'];
			$fonts[] = ['class' => 'fa-ban','title' => 'Ban'];
			$fonts[] = ['class' => 'fa-arrow-left','title' => 'Arrow Left'];
			$fonts[] = ['class' => 'fa-arrow-right','title' => 'Arrow Right'];
			$fonts[] = ['class' => 'fa-arrow-up','title' => 'Arrow Up'];
			$fonts[] = ['class' => 'fa-arrow-down','title' => 'Arrow Down'];
			$fonts[] = ['class' => 'fa-mail-forward','title' => 'Mail Forward'];
			$fonts[] = ['class' => 'fa-share','title' => 'Share'];
			$fonts[] = ['class' => 'fa-expand','title' => 'Expand'];
			$fonts[] = ['class' => 'fa-compress','title' => 'Compress'];
			$fonts[] = ['class' => 'fa-plus','title' => 'Plus'];
			$fonts[] = ['class' => 'fa-minus','title' => 'Minus'];
			$fonts[] = ['class' => 'fa-asterisk','title' => 'Asterisk'];
			$fonts[] = ['class' => 'fa-exclamation-circle','title' => 'Exclamation Circle'];
			$fonts[] = ['class' => 'fa-gift','title' => 'Gift'];
			$fonts[] = ['class' => 'fa-leaf','title' => 'Leaf'];
			$fonts[] = ['class' => 'fa-fire','title' => 'Fire'];
			$fonts[] = ['class' => 'fa-eye','title' => 'Eye'];
			$fonts[] = ['class' => 'fa-eye-slash','title' => 'Eye Slash'];
			$fonts[] = ['class' => 'fa-warning','title' => 'Warning'];
			$fonts[] = ['class' => 'fa-exclamation-triangle','title' => 'Exclamation Triangle'];
			$fonts[] = ['class' => 'fa-plane','title' => 'Plane'];
			$fonts[] = ['class' => 'fa-calendar','title' => 'Calendar'];
			$fonts[] = ['class' => 'fa-random','title' => 'Random'];
			$fonts[] = ['class' => 'fa-comment','title' => 'Comment'];
			$fonts[] = ['class' => 'fa-magnet','title' => 'Magnet'];
			$fonts[] = ['class' => 'fa-chevron-up','title' => 'Chevron Up'];
			$fonts[] = ['class' => 'fa-chevron-down','title' => 'Chevron Down'];
			$fonts[] = ['class' => 'fa-retweet','title' => 'Retweet'];
			$fonts[] = ['class' => 'fa-shopping-cart','title' => 'Shopping Cart'];
			$fonts[] = ['class' => 'fa-folder','title' => 'Folder'];
			$fonts[] = ['class' => 'fa-folder-open','title' => 'Folder Open'];
			$fonts[] = ['class' => 'fa-arrows-v','title' => 'Arrows V'];
			$fonts[] = ['class' => 'fa-arrows-h','title' => 'Arrows H'];
			$fonts[] = ['class' => 'fa-bar-chart-o','title' => 'Bar Chart O'];
			$fonts[] = ['class' => 'fa-bar-chart','title' => 'Bar Chart'];
			$fonts[] = ['class' => 'fa-twitter-square','title' => 'Twitter Square'];
			$fonts[] = ['class' => 'fa-facebook-square','title' => 'Facebook Square'];
			$fonts[] = ['class' => 'fa-camera-retro','title' => 'Camera Retro'];
			$fonts[] = ['class' => 'fa-key','title' => 'Key'];
			$fonts[] = ['class' => 'fa-gears','title' => 'Gears'];
			$fonts[] = ['class' => 'fa-cogs','title' => 'Cogs'];
			$fonts[] = ['class' => 'fa-comments','title' => 'Comments'];
			$fonts[] = ['class' => 'fa-thumbs-o-up','title' => 'Thumbs O Up'];
			$fonts[] = ['class' => 'fa-thumbs-o-down','title' => 'Thumbs O Down'];
			$fonts[] = ['class' => 'fa-star-half','title' => 'Star Half'];
			$fonts[] = ['class' => 'fa-heart-o','title' => 'Heart O'];
			$fonts[] = ['class' => 'fa-sign-out','title' => 'Sign Out'];
			$fonts[] = ['class' => 'fa-linkedin-square','title' => 'LinkedIn Square'];
			$fonts[] = ['class' => 'fa-thumb-tack','title' => 'Thumb Tack'];
			$fonts[] = ['class' => 'fa-external-link','title' => 'External Link'];
			$fonts[] = ['class' => 'fa-sign-in','title' => 'Sign In'];
			$fonts[] = ['class' => 'fa-trophy','title' => 'Trophy'];
			$fonts[] = ['class' => 'fa-github-square','title' => 'Github Square'];
			$fonts[] = ['class' => 'fa-upload','title' => 'Upload'];
			$fonts[] = ['class' => 'fa-lemon-o','title' => 'Lemon O'];
			$fonts[] = ['class' => 'fa-phone','title' => 'Phone'];
			$fonts[] = ['class' => 'fa-square-o','title' => 'Square O'];
			$fonts[] = ['class' => 'fa-bookmark-o','title' => 'Bookmark O'];
			$fonts[] = ['class' => 'fa-phone-square','title' => 'Phone Square'];
			$fonts[] = ['class' => 'fa-twitter','title' => 'Twitter'];
			$fonts[] = ['class' => 'fa-facebook-f','title' => 'Facebook F'];
			$fonts[] = ['class' => 'fa-facebook','title' => 'Facebook'];
			$fonts[] = ['class' => 'fa-github','title' => 'Github'];
			$fonts[] = ['class' => 'fa-unlock','title' => 'Unlock'];
			$fonts[] = ['class' => 'fa-credit-card','title' => 'Credit Card'];
			$fonts[] = ['class' => 'fa-feed','title' => 'Feed'];
			$fonts[] = ['class' => 'fa-rss','title' => 'Rss'];
			$fonts[] = ['class' => 'fa-hdd-o','title' => 'Hdd O'];
			$fonts[] = ['class' => 'fa-bullhorn','title' => 'Bullhorn'];
			$fonts[] = ['class' => 'fa-bell','title' => 'Bell'];
			$fonts[] = ['class' => 'fa-certificate','title' => 'Certificate'];
			$fonts[] = ['class' => 'fa-hand-o-right','title' => 'Hand O Right'];
			$fonts[] = ['class' => 'fa-hand-o-left','title' => 'Hand O Left'];
			$fonts[] = ['class' => 'fa-hand-o-up','title' => 'Hand O Up'];
			$fonts[] = ['class' => 'fa-hand-o-down','title' => 'Hand O Down'];
			$fonts[] = ['class' => 'fa-arrow-circle-left','title' => 'Arrow Circle Left'];
			$fonts[] = ['class' => 'fa-arrow-circle-right','title' => 'Arrow Circle Right'];
			$fonts[] = ['class' => 'fa-arrow-circle-up','title' => 'Arrow Circle Up'];
			$fonts[] = ['class' => 'fa-arrow-circle-down','title' => 'Arrow Circle Down'];
			$fonts[] = ['class' => 'fa-globe','title' => 'Globe'];
			$fonts[] = ['class' => 'fa-wrench','title' => 'Wrench'];
			$fonts[] = ['class' => 'fa-tasks','title' => 'Tasks'];
			$fonts[] = ['class' => 'fa-filter','title' => 'Filter'];
			$fonts[] = ['class' => 'fa-briefcase','title' => 'Briefcase'];
			$fonts[] = ['class' => 'fa-arrows-alt','title' => 'Arrows Alt'];
			$fonts[] = ['class' => 'fa-group','title' => 'Group'];
			$fonts[] = ['class' => 'fa-users','title' => 'Users'];
			$fonts[] = ['class' => 'fa-chain','title' => 'Chain'];
			$fonts[] = ['class' => 'fa-link','title' => 'Link'];
			$fonts[] = ['class' => 'fa-cloud','title' => 'Cloud'];
			$fonts[] = ['class' => 'fa-flask','title' => 'Flask'];
			$fonts[] = ['class' => 'fa-cut','title' => 'Cut'];
			$fonts[] = ['class' => 'fa-scissors','title' => 'Scissors'];
			$fonts[] = ['class' => 'fa-copy','title' => 'Copy'];
			$fonts[] = ['class' => 'fa-files-o','title' => 'Files O'];
			$fonts[] = ['class' => 'fa-paperclip','title' => 'Paperclip'];
			$fonts[] = ['class' => 'fa-save','title' => 'Save'];
			$fonts[] = ['class' => 'fa-floppy-o','title' => 'Floppy O'];
			$fonts[] = ['class' => 'fa-square','title' => 'Square'];
			$fonts[] = ['class' => 'fa-navicon','title' => 'Navicon'];
			$fonts[] = ['class' => 'fa-reorder','title' => 'Reorder'];
			$fonts[] = ['class' => 'fa-bars','title' => 'Bars'];
			$fonts[] = ['class' => 'fa-list-ul','title' => 'List Ul'];
			$fonts[] = ['class' => 'fa-list-ol','title' => 'List Ol'];
			$fonts[] = ['class' => 'fa-strikethrough','title' => 'Strikethrough'];
			$fonts[] = ['class' => 'fa-underline','title' => 'Underline'];
			$fonts[] = ['class' => 'fa-table','title' => 'Table'];
			$fonts[] = ['class' => 'fa-magic','title' => 'Magic'];
			$fonts[] = ['class' => 'fa-truck','title' => 'Truck'];
			$fonts[] = ['class' => 'fa-pinterest','title' => 'Pinterest'];
			$fonts[] = ['class' => 'fa-pinterest-square','title' => 'Pinterest Square'];
			$fonts[] = ['class' => 'fa-google-plus-square','title' => 'Google Plus Square'];
			$fonts[] = ['class' => 'fa-google-plus','title' => 'Google Plus'];
			$fonts[] = ['class' => 'fa-money','title' => 'Money'];
			$fonts[] = ['class' => 'fa-caret-down','title' => 'Caret Down'];
			$fonts[] = ['class' => 'fa-caret-up','title' => 'Caret Up'];
			$fonts[] = ['class' => 'fa-caret-left','title' => 'Caret Left'];
			$fonts[] = ['class' => 'fa-caret-right','title' => 'Caret Right'];
			$fonts[] = ['class' => 'fa-columns','title' => 'Columns'];
			$fonts[] = ['class' => 'fa-unsorted','title' => 'Unsorted'];
			$fonts[] = ['class' => 'fa-sort','title' => 'Sort'];
			$fonts[] = ['class' => 'fa-sort-down','title' => 'Sort Down'];
			$fonts[] = ['class' => 'fa-sort-desc','title' => 'Sort Desc'];
			$fonts[] = ['class' => 'fa-sort-up','title' => 'Sort Up'];
			$fonts[] = ['class' => 'fa-sort-asc','title' => 'Sort Asc'];
			$fonts[] = ['class' => 'fa-envelope','title' => 'Envelope'];
			$fonts[] = ['class' => 'fa-linkedin','title' => 'LinkedIn'];
			$fonts[] = ['class' => 'fa-rotate-left','title' => 'Rotate Left'];
			$fonts[] = ['class' => 'fa-undo','title' => 'Undo'];
			$fonts[] = ['class' => 'fa-legal','title' => 'Legal'];
			$fonts[] = ['class' => 'fa-gavel','title' => 'Gavel'];
			$fonts[] = ['class' => 'fa-dashboard','title' => 'Dashboard'];
			$fonts[] = ['class' => 'fa-tachometer','title' => 'Tachometer'];
			$fonts[] = ['class' => 'fa-comment-o','title' => 'Comment O'];
			$fonts[] = ['class' => 'fa-comments-o','title' => 'Comments O'];
			$fonts[] = ['class' => 'fa-flash','title' => 'Flash'];
			$fonts[] = ['class' => 'fa-bolt','title' => 'Bolt'];
			$fonts[] = ['class' => 'fa-sitemap','title' => 'Sitemap'];
			$fonts[] = ['class' => 'fa-umbrella','title' => 'Umbrella'];
			$fonts[] = ['class' => 'fa-paste','title' => 'Paste'];
			$fonts[] = ['class' => 'fa-clipboard','title' => 'Clipboard'];
			$fonts[] = ['class' => 'fa-lightbulb-o','title' => 'Lightbulb O'];
			$fonts[] = ['class' => 'fa-exchange','title' => 'Exchange'];
			$fonts[] = ['class' => 'fa-cloud-download','title' => 'Cloud Download'];
			$fonts[] = ['class' => 'fa-cloud-upload','title' => 'Cloud Upload'];
			$fonts[] = ['class' => 'fa-user-md','title' => 'User Md'];
			$fonts[] = ['class' => 'fa-stethoscope','title' => 'Stethoscope'];
			$fonts[] = ['class' => 'fa-suitcase','title' => 'Suitcase'];
			$fonts[] = ['class' => 'fa-bell-o','title' => 'Bell O'];
			$fonts[] = ['class' => 'fa-coffee','title' => 'Coffee'];
			$fonts[] = ['class' => 'fa-cutlery','title' => 'Cutlery'];
			$fonts[] = ['class' => 'fa-file-text-o','title' => 'File Text O'];
			$fonts[] = ['class' => 'fa-building-o','title' => 'Building O'];
			$fonts[] = ['class' => 'fa-hospital-o','title' => 'Hospital O'];
			$fonts[] = ['class' => 'fa-ambulance','title' => 'Ambulance'];
			$fonts[] = ['class' => 'fa-medkit','title' => 'Med Kit'];
			$fonts[] = ['class' => 'fa-fighter-jet','title' => 'Fighter Jet'];
			$fonts[] = ['class' => 'fa-beer','title' => 'Beer'];
			$fonts[] = ['class' => 'fa-h-square','title' => 'H Square'];
			$fonts[] = ['class' => 'fa-plus-square','title' => 'Plus Square'];
			$fonts[] = ['class' => 'fa-angle-double-left','title' => 'Angle Double Left'];
			$fonts[] = ['class' => 'fa-angle-double-right','title' => 'Angle Double Right'];
			$fonts[] = ['class' => 'fa-angle-double-up','title' => 'Angle Double Up'];
			$fonts[] = ['class' => 'fa-angle-double-down','title' => 'Angle Double Down'];
			$fonts[] = ['class' => 'fa-angle-left','title' => 'Angle Left'];
			$fonts[] = ['class' => 'fa-angle-right','title' => 'Angle Right'];
			$fonts[] = ['class' => 'fa-angle-up','title' => 'Angle Up'];
			$fonts[] = ['class' => 'fa-angle-down','title' => 'Angle Down'];
			$fonts[] = ['class' => 'fa-desktop','title' => 'Desktop'];
			$fonts[] = ['class' => 'fa-laptop','title' => 'Laptop'];
			$fonts[] = ['class' => 'fa-tablet','title' => 'Tablet'];
			$fonts[] = ['class' => 'fa-mobile-phone','title' => 'Mobile Phone'];
			$fonts[] = ['class' => 'fa-mobile','title' => 'Mobile'];
			$fonts[] = ['class' => 'fa-circle-o','title' => 'Circle O'];
			$fonts[] = ['class' => 'fa-quote-left','title' => 'Quote Left'];
			$fonts[] = ['class' => 'fa-quote-right','title' => 'Quote Right'];
			$fonts[] = ['class' => 'fa-spinner','title' => 'Spinner'];
			$fonts[] = ['class' => 'fa-circle','title' => 'Circle'];
			$fonts[] = ['class' => 'fa-mail-reply','title' => 'Mail Reply'];
			$fonts[] = ['class' => 'fa-reply','title' => 'Reply'];
			$fonts[] = ['class' => 'fa-github-alt','title' => 'Github Alt'];
			$fonts[] = ['class' => 'fa-folder-o','title' => 'Folder O'];
			$fonts[] = ['class' => 'fa-folder-open-o','title' => 'Folder Open O'];
			$fonts[] = ['class' => 'fa-smile-o','title' => 'Smile O'];
			$fonts[] = ['class' => 'fa-frown-o','title' => 'Frown O'];
			$fonts[] = ['class' => 'fa-meh-o','title' => 'Meh O'];
			$fonts[] = ['class' => 'fa-gamepad','title' => 'Gamepad'];
			$fonts[] = ['class' => 'fa-keyboard-o','title' => 'Keyboard O'];
			$fonts[] = ['class' => 'fa-flag-o','title' => 'Flag O'];
			$fonts[] = ['class' => 'fa-flag-checkered','title' => 'Flag Checkered'];
			$fonts[] = ['class' => 'fa-terminal','title' => 'Terminal'];
			$fonts[] = ['class' => 'fa-code','title' => 'Code'];
			$fonts[] = ['class' => 'fa-mail-reply-all','title' => 'Mail Reply All'];
			$fonts[] = ['class' => 'fa-reply-all','title' => 'Reply All'];
			$fonts[] = ['class' => 'fa-star-half-empty','title' => 'Star Half Empty'];
			$fonts[] = ['class' => 'fa-star-half-full','title' => 'Star Half Full'];
			$fonts[] = ['class' => 'fa-star-half-o','title' => 'Star Half O'];
			$fonts[] = ['class' => 'fa-location-arrow','title' => 'Location Arrow'];
			$fonts[] = ['class' => 'fa-crop','title' => 'Crop'];
			$fonts[] = ['class' => 'fa-code-fork','title' => 'Code Fork'];
			$fonts[] = ['class' => 'fa-unlink','title' => 'Unlink'];
			$fonts[] = ['class' => 'fa-chain-broken','title' => 'Chain Broken'];
			$fonts[] = ['class' => 'fa-question','title' => 'Question'];
			$fonts[] = ['class' => 'fa-info','title' => 'Info'];
			$fonts[] = ['class' => 'fa-exclamation','title' => 'Exclamation'];
			$fonts[] = ['class' => 'fa-superscript','title' => 'Superscript'];
			$fonts[] = ['class' => 'fa-subscript','title' => 'Subscript'];
			$fonts[] = ['class' => 'fa-eraser','title' => 'Eraser'];
			$fonts[] = ['class' => 'fa-puzzle-piece','title' => 'Puzzle Piece'];
			$fonts[] = ['class' => 'fa-microphone','title' => 'Microphone'];
			$fonts[] = ['class' => 'fa-microphone-slash','title' => 'Microphone Slash'];
			$fonts[] = ['class' => 'fa-shield','title' => 'Shield'];
			$fonts[] = ['class' => 'fa-calendar-o','title' => 'Calendar O'];
			$fonts[] = ['class' => 'fa-fire-extinguisher','title' => 'Fire Extinguisher'];
			$fonts[] = ['class' => 'fa-rocket','title' => 'Rocket'];
			$fonts[] = ['class' => 'fa-maxcdn','title' => 'Maxcdn'];
			$fonts[] = ['class' => 'fa-chevron-circle-left','title' => 'Chevron Circle Left'];
			$fonts[] = ['class' => 'fa-chevron-circle-right','title' => 'Chevron Circle Right'];
			$fonts[] = ['class' => 'fa-chevron-circle-up','title' => 'Chevron Circle Up'];
			$fonts[] = ['class' => 'fa-chevron-circle-down','title' => 'Chevron Circle Down'];
			$fonts[] = ['class' => 'fa-html5','title' => 'Html5'];
			$fonts[] = ['class' => 'fa-css3','title' => 'Css3'];
			$fonts[] = ['class' => 'fa-anchor','title' => 'Anchor'];
			$fonts[] = ['class' => 'fa-unlock-alt','title' => 'Unlock Alt'];
			$fonts[] = ['class' => 'fa-bullseye','title' => 'Bullseye'];
			$fonts[] = ['class' => 'fa-ellipsis-h','title' => 'Ellipsis H'];
			$fonts[] = ['class' => 'fa-ellipsis-v','title' => 'Ellipsis V'];
			$fonts[] = ['class' => 'fa-rss-square','title' => 'Rss Square'];
			$fonts[] = ['class' => 'fa-play-circle','title' => 'Play Circle'];
			$fonts[] = ['class' => 'fa-minus-square','title' => 'Minus Square'];
			$fonts[] = ['class' => 'fa-minus-square-o','title' => 'Minus Square O'];
			$fonts[] = ['class' => 'fa-level-up','title' => 'Level Up'];
			$fonts[] = ['class' => 'fa-level-down','title' => 'Level Down'];
			$fonts[] = ['class' => 'fa-check-square','title' => 'Check Square'];
			$fonts[] = ['class' => 'fa-pencil-square','title' => 'Pencil Square'];
			$fonts[] = ['class' => 'fa-external-link-square','title' => 'External Link Square'];
			$fonts[] = ['class' => 'fa-share-square','title' => 'Share Square'];
			$fonts[] = ['class' => 'fa-compass','title' => 'Compass'];
			$fonts[] = ['class' => 'fa-toggle-down','title' => 'Toggle Down'];
			$fonts[] = ['class' => 'fa-caret-square-o-down','title' => 'Caret Square O Down'];
			$fonts[] = ['class' => 'fa-toggle-up','title' => 'Toggle Up'];
			$fonts[] = ['class' => 'fa-caret-square-o-up','title' => 'Caret Square O Up'];
			$fonts[] = ['class' => 'fa-toggle-right','title' => 'Toggle Right'];
			$fonts[] = ['class' => 'fa-caret-square-o-right','title' => 'Caret Square O Right'];
			$fonts[] = ['class' => 'fa-euro','title' => 'Euro'];
			$fonts[] = ['class' => 'fa-eur','title' => 'EUR'];
			$fonts[] = ['class' => 'fa-gbp','title' => 'GBP'];
			$fonts[] = ['class' => 'fa-dollar','title' => 'Dollar'];
			$fonts[] = ['class' => 'fa-usd','title' => 'USD'];
			$fonts[] = ['class' => 'fa-rupee','title' => 'Rupee'];
			$fonts[] = ['class' => 'fa-inr','title' => 'INR'];
			$fonts[] = ['class' => 'fa-cny','title' => 'CNY'];
			$fonts[] = ['class' => 'fa-rmb','title' => 'RMB'];
			$fonts[] = ['class' => 'fa-yen','title' => 'Yen'];
			$fonts[] = ['class' => 'fa-jpy','title' => 'JPY'];
			$fonts[] = ['class' => 'fa-ruble','title' => 'Ruble'];
			$fonts[] = ['class' => 'fa-rouble','title' => 'Rouble'];
			$fonts[] = ['class' => 'fa-rub','title' => 'RUB'];
			$fonts[] = ['class' => 'fa-won','title' => 'Won'];
			$fonts[] = ['class' => 'fa-krw','title' => 'KRW'];
			$fonts[] = ['class' => 'fa-bitcoin','title' => 'Bitcoin'];
			$fonts[] = ['class' => 'fa-btc','title' => 'BTC'];
			$fonts[] = ['class' => 'fa-file','title' => 'File'];
			$fonts[] = ['class' => 'fa-file-text','title' => 'File Text'];
			$fonts[] = ['class' => 'fa-sort-alpha-asc','title' => 'Sort Alpha Asc'];
			$fonts[] = ['class' => 'fa-sort-alpha-desc','title' => 'Sort Alpha Desc'];
			$fonts[] = ['class' => 'fa-sort-amount-asc','title' => 'Sort Amount Asc'];
			$fonts[] = ['class' => 'fa-sort-amount-desc','title' => 'Sort Amount Desc'];
			$fonts[] = ['class' => 'fa-sort-numeric-asc','title' => 'Sort Numeric Asc'];
			$fonts[] = ['class' => 'fa-sort-numeric-desc','title' => 'Sort Numeric Desc'];
			$fonts[] = ['class' => 'fa-thumbs-up','title' => 'Thumbs Up'];
			$fonts[] = ['class' => 'fa-thumbs-down','title' => 'Thumbs Down'];
			$fonts[] = ['class' => 'fa-youtube-square','title' => 'YouTube Square'];
			$fonts[] = ['class' => 'fa-youtube','title' => 'YouTube'];
			$fonts[] = ['class' => 'fa-xing','title' => 'Xing'];
			$fonts[] = ['class' => 'fa-xing-square','title' => 'Xing Square'];
			$fonts[] = ['class' => 'fa-youtube-play','title' => 'YouTube Play'];
			$fonts[] = ['class' => 'fa-dropbox','title' => 'Dropbox'];
			$fonts[] = ['class' => 'fa-stack-overflow','title' => 'Stack Overflow'];
			$fonts[] = ['class' => 'fa-instagram','title' => 'Instagram'];
			$fonts[] = ['class' => 'fa-flickr','title' => 'Flickr'];
			$fonts[] = ['class' => 'fa-adn','title' => 'Adn'];
			$fonts[] = ['class' => 'fa-bitbucket','title' => 'Bitbucket'];
			$fonts[] = ['class' => 'fa-bitbucket-square','title' => 'Bitbucket Square'];
			$fonts[] = ['class' => 'fa-tumblr','title' => 'Tumblr'];
			$fonts[] = ['class' => 'fa-tumblr-square','title' => 'Tumblr Square'];
			$fonts[] = ['class' => 'fa-long-arrow-down','title' => 'Long Arrow Down'];
			$fonts[] = ['class' => 'fa-long-arrow-up','title' => 'Long Arrow Up'];
			$fonts[] = ['class' => 'fa-long-arrow-left','title' => 'Long Arrow Left'];
			$fonts[] = ['class' => 'fa-long-arrow-right','title' => 'Long Arrow Right'];
			$fonts[] = ['class' => 'fa-apple','title' => 'Apple'];
			$fonts[] = ['class' => 'fa-windows','title' => 'Windows'];
			$fonts[] = ['class' => 'fa-android','title' => 'Android'];
			$fonts[] = ['class' => 'fa-linux','title' => 'Linux'];
			$fonts[] = ['class' => 'fa-dribbble','title' => 'Dribbble'];
			$fonts[] = ['class' => 'fa-skype','title' => 'Skype'];
			$fonts[] = ['class' => 'fa-foursquare','title' => 'Foursquare'];
			$fonts[] = ['class' => 'fa-trello','title' => 'Trello'];
			$fonts[] = ['class' => 'fa-female','title' => 'Female'];
			$fonts[] = ['class' => 'fa-male','title' => 'Male'];
			$fonts[] = ['class' => 'fa-gittip','title' => 'Gittip'];
			$fonts[] = ['class' => 'fa-gratipay','title' => 'Gratipay'];
			$fonts[] = ['class' => 'fa-sun-o','title' => 'Sun O'];
			$fonts[] = ['class' => 'fa-moon-o','title' => 'Moon O'];
			$fonts[] = ['class' => 'fa-archive','title' => 'Archive'];
			$fonts[] = ['class' => 'fa-bug','title' => 'Bug'];
			$fonts[] = ['class' => 'fa-vk','title' => 'Vk'];
			$fonts[] = ['class' => 'fa-weibo','title' => 'Weibo'];
			$fonts[] = ['class' => 'fa-renren','title' => 'Renren'];
			$fonts[] = ['class' => 'fa-pagelines','title' => 'Pagelines'];
			$fonts[] = ['class' => 'fa-stack-exchange','title' => 'Stack Exchange'];
			$fonts[] = ['class' => 'fa-arrow-circle-o-right','title' => 'Arrow Circle O Right'];
			$fonts[] = ['class' => 'fa-arrow-circle-o-left','title' => 'Arrow Circle O Left'];
			$fonts[] = ['class' => 'fa-toggle-left','title' => 'Toggle Left'];
			$fonts[] = ['class' => 'fa-caret-square-o-left','title' => 'Caret Square O Left'];
			$fonts[] = ['class' => 'fa-dot-circle-o','title' => 'Dot Circle O'];
			$fonts[] = ['class' => 'fa-wheelchair','title' => 'Wheelchair'];
			$fonts[] = ['class' => 'fa-vimeo-square','title' => 'Vimeo Square'];
			$fonts[] = ['class' => 'fa-turkish-lira','title' => 'Turkish Lira'];
			$fonts[] = ['class' => 'fa-try','title' => 'TRY'];
			$fonts[] = ['class' => 'fa-plus-square-o','title' => 'Plus Square O'];
			$fonts[] = ['class' => 'fa-space-shuttle','title' => 'Space Shuttle'];
			$fonts[] = ['class' => 'fa-slack','title' => 'Slack'];
			$fonts[] = ['class' => 'fa-envelope-square','title' => 'Envelope Square'];
			$fonts[] = ['class' => 'fa-wordpress','title' => 'Wordpress'];
			$fonts[] = ['class' => 'fa-openid','title' => 'OpenId'];
			$fonts[] = ['class' => 'fa-institution','title' => 'Institution'];
			$fonts[] = ['class' => 'fa-bank','title' => 'Bank'];
			$fonts[] = ['class' => 'fa-university','title' => 'University'];
			$fonts[] = ['class' => 'fa-mortar-board','title' => 'Mortar Board'];
			$fonts[] = ['class' => 'fa-graduation-cap','title' => 'Graduation Cap'];
			$fonts[] = ['class' => 'fa-yahoo','title' => 'Yahoo'];
			$fonts[] = ['class' => 'fa-google','title' => 'Google'];
			$fonts[] = ['class' => 'fa-reddit','title' => 'Reddit'];
			$fonts[] = ['class' => 'fa-reddit-square','title' => 'Reddit Square'];
			$fonts[] = ['class' => 'fa-stumbleupon-circle','title' => 'Stumbleupon Circle'];
			$fonts[] = ['class' => 'fa-stumbleupon','title' => 'Stumbleupon'];
			$fonts[] = ['class' => 'fa-delicious','title' => 'Delicious'];
			$fonts[] = ['class' => 'fa-digg','title' => 'Digg'];
			$fonts[] = ['class' => 'fa-pied-piper-pp','title' => 'Pied Piper Pp'];
			$fonts[] = ['class' => 'fa-pied-piper-alt','title' => 'Pied Piper Alt'];
			$fonts[] = ['class' => 'fa-drupal','title' => 'Drupal'];
			$fonts[] = ['class' => 'fa-joomla','title' => 'Joomla'];
			$fonts[] = ['class' => 'fa-language','title' => 'Language'];
			$fonts[] = ['class' => 'fa-fax','title' => 'Fax'];
			$fonts[] = ['class' => 'fa-building','title' => 'Building'];
			$fonts[] = ['class' => 'fa-child','title' => 'Child'];
			$fonts[] = ['class' => 'fa-paw','title' => 'Paw'];
			$fonts[] = ['class' => 'fa-spoon','title' => 'Spoon'];
			$fonts[] = ['class' => 'fa-cube','title' => 'Cube'];
			$fonts[] = ['class' => 'fa-cubes','title' => 'Cubes'];
			$fonts[] = ['class' => 'fa-behance','title' => 'Behance'];
			$fonts[] = ['class' => 'fa-behance-square','title' => 'Behance Square'];
			$fonts[] = ['class' => 'fa-steam','title' => 'Steam'];
			$fonts[] = ['class' => 'fa-steam-square','title' => 'Steam Square'];
			$fonts[] = ['class' => 'fa-recycle','title' => 'Recycle'];
			$fonts[] = ['class' => 'fa-automobile','title' => 'Automobile'];
			$fonts[] = ['class' => 'fa-car','title' => 'Car'];
			$fonts[] = ['class' => 'fa-cab','title' => 'Cab'];
			$fonts[] = ['class' => 'fa-taxi','title' => 'Taxi'];
			$fonts[] = ['class' => 'fa-tree','title' => 'Tree'];
			$fonts[] = ['class' => 'fa-spotify','title' => 'Spotify'];
			$fonts[] = ['class' => 'fa-deviantart','title' => 'DeviantArt'];
			$fonts[] = ['class' => 'fa-soundcloud','title' => 'SoundCloud'];
			$fonts[] = ['class' => 'fa-database','title' => 'Database'];
			$fonts[] = ['class' => 'fa-file-pdf-o','title' => 'File Pdf O'];
			$fonts[] = ['class' => 'fa-file-word-o','title' => 'File Word O'];
			$fonts[] = ['class' => 'fa-file-excel-o','title' => 'File Excel O'];
			$fonts[] = ['class' => 'fa-file-powerpoint-o','title' => 'File Powerpoint O'];
			$fonts[] = ['class' => 'fa-file-photo-o','title' => 'File Photo O'];
			$fonts[] = ['class' => 'fa-file-picture-o','title' => 'File Picture O'];
			$fonts[] = ['class' => 'fa-file-image-o','title' => 'File Image O'];
			$fonts[] = ['class' => 'fa-file-zip-o','title' => 'File Zip O'];
			$fonts[] = ['class' => 'fa-file-archive-o','title' => 'File Archive O'];
			$fonts[] = ['class' => 'fa-file-sound-o','title' => 'File Sound O'];
			$fonts[] = ['class' => 'fa-file-audio-o','title' => 'File Audio O'];
			$fonts[] = ['class' => 'fa-file-movie-o','title' => 'File Movie O'];
			$fonts[] = ['class' => 'fa-file-video-o','title' => 'File Video O'];
			$fonts[] = ['class' => 'fa-file-code-o','title' => 'File Code O'];
			$fonts[] = ['class' => 'fa-vine','title' => 'Vine'];
			$fonts[] = ['class' => 'fa-codepen','title' => 'Codepen'];
			$fonts[] = ['class' => 'fa-jsfiddle','title' => 'JsFiddle'];
			$fonts[] = ['class' => 'fa-life-bouy','title' => 'Life Bouy'];
			$fonts[] = ['class' => 'fa-life-buoy','title' => 'Life Buoy'];
			$fonts[] = ['class' => 'fa-life-saver','title' => 'Life Saver'];
			$fonts[] = ['class' => 'fa-support','title' => 'Support'];
			$fonts[] = ['class' => 'fa-life-ring','title' => 'Life Ring'];
			$fonts[] = ['class' => 'fa-circle-o-notch','title' => 'Circle O Notch'];
			$fonts[] = ['class' => 'fa-ra','title' => 'Ra'];
			$fonts[] = ['class' => 'fa-resistance','title' => 'Resistance'];
			$fonts[] = ['class' => 'fa-rebel','title' => 'Rebel'];
			$fonts[] = ['class' => 'fa-ge','title' => 'Ge'];
			$fonts[] = ['class' => 'fa-empire','title' => 'Empire'];
			$fonts[] = ['class' => 'fa-git-square','title' => 'Git Square'];
			$fonts[] = ['class' => 'fa-git','title' => 'Git'];
			$fonts[] = ['class' => 'fa-y-combinator-square','title' => 'Y Combinator Square'];
			$fonts[] = ['class' => 'fa-yc-square','title' => 'Yc Square'];
			$fonts[] = ['class' => 'fa-hacker-news','title' => 'Hacker News'];
			$fonts[] = ['class' => 'fa-tencent-weibo','title' => 'Tencent Weibo'];
			$fonts[] = ['class' => 'fa-qq','title' => 'Qq'];
			$fonts[] = ['class' => 'fa-wechat','title' => 'WeChat'];
			$fonts[] = ['class' => 'fa-weixin','title' => 'Weixin'];
			$fonts[] = ['class' => 'fa-send','title' => 'Send'];
			$fonts[] = ['class' => 'fa-paper-plane','title' => 'Paper Plane'];
			$fonts[] = ['class' => 'fa-send-o','title' => 'Send O'];
			$fonts[] = ['class' => 'fa-paper-plane-o','title' => 'Paper Plane O'];
			$fonts[] = ['class' => 'fa-history','title' => 'History'];
			$fonts[] = ['class' => 'fa-circle-thin','title' => 'Circle Thin'];
			$fonts[] = ['class' => 'fa-header','title' => 'Header'];
			$fonts[] = ['class' => 'fa-paragraph','title' => 'Paragraph'];
			$fonts[] = ['class' => 'fa-sliders','title' => 'Sliders'];
			$fonts[] = ['class' => 'fa-share-alt','title' => 'Share Alt'];
			$fonts[] = ['class' => 'fa-share-alt-square','title' => 'Share Alt Square'];
			$fonts[] = ['class' => 'fa-bomb','title' => 'Bomb'];
			$fonts[] = ['class' => 'fa-soccer-ball-o','title' => 'Soccer Ball O'];
			$fonts[] = ['class' => 'fa-futbol-o','title' => 'Futbol O'];
			$fonts[] = ['class' => 'fa-tty','title' => 'Tty'];
			$fonts[] = ['class' => 'fa-binoculars','title' => 'Binoculars'];
			$fonts[] = ['class' => 'fa-plug','title' => 'Plug'];
			$fonts[] = ['class' => 'fa-slideshare','title' => 'Slideshare'];
			$fonts[] = ['class' => 'fa-twitch','title' => 'Twitch'];
			$fonts[] = ['class' => 'fa-yelp','title' => 'Yelp'];
			$fonts[] = ['class' => 'fa-newspaper-o','title' => 'Newspaper O'];
			$fonts[] = ['class' => 'fa-wifi','title' => 'Wifi'];
			$fonts[] = ['class' => 'fa-calculator','title' => 'Calculator'];
			$fonts[] = ['class' => 'fa-paypal','title' => 'Paypal'];
			$fonts[] = ['class' => 'fa-google-wallet','title' => 'Google Wallet'];
			$fonts[] = ['class' => 'fa-cc-visa','title' => 'CC Visa'];
			$fonts[] = ['class' => 'fa-cc-mastercard','title' => 'CC Mastercard'];
			$fonts[] = ['class' => 'fa-cc-discover','title' => 'CC Discover'];
			$fonts[] = ['class' => 'fa-cc-amex','title' => 'CC Amex'];
			$fonts[] = ['class' => 'fa-cc-paypal','title' => 'CC Paypal'];
			$fonts[] = ['class' => 'fa-cc-stripe','title' => 'CC Stripe'];
			$fonts[] = ['class' => 'fa-bell-slash','title' => 'Bell Slash'];
			$fonts[] = ['class' => 'fa-bell-slash-o','title' => 'Bell Slash O'];
			$fonts[] = ['class' => 'fa-copyright','title' => 'Copyright'];
			$fonts[] = ['class' => 'fa-at','title' => 'At'];
			$fonts[] = ['class' => 'fa-eyedropper','title' => 'EyeDropper'];
			$fonts[] = ['class' => 'fa-paint-brush','title' => 'Paint Brush'];
			$fonts[] = ['class' => 'fa-birthday-cake','title' => 'Birthday Cake'];
			$fonts[] = ['class' => 'fa-area-chart','title' => 'Area Chart'];
			$fonts[] = ['class' => 'fa-pie-chart','title' => 'Pie Chart'];
			$fonts[] = ['class' => 'fa-line-chart','title' => 'Line Chart'];
			$fonts[] = ['class' => 'fa-lastfm','title' => 'LastFM'];
			$fonts[] = ['class' => 'fa-lastfm-square','title' => 'LastFM Square'];
			$fonts[] = ['class' => 'fa-toggle-off','title' => 'Toggle Off'];
			$fonts[] = ['class' => 'fa-toggle-on','title' => 'Toggle On'];
			$fonts[] = ['class' => 'fa-bicycle','title' => 'Bicycle'];
			$fonts[] = ['class' => 'fa-bus','title' => 'Bus'];
			$fonts[] = ['class' => 'fa-ioxhost','title' => 'Ioxhost'];
			$fonts[] = ['class' => 'fa-angellist','title' => 'Angellist'];
			$fonts[] = ['class' => 'fa-cc','title' => 'CC'];
			$fonts[] = ['class' => 'fa-shekel','title' => 'Shekel'];
			$fonts[] = ['class' => 'fa-sheqel','title' => 'Sheqel'];
			$fonts[] = ['class' => 'fa-ils','title' => 'ILS'];
			$fonts[] = ['class' => 'fa-meanpath','title' => 'MeanPath'];
			$fonts[] = ['class' => 'fa-buysellads','title' => 'BuySellAds'];
			$fonts[] = ['class' => 'fa-connectdevelop','title' => 'ConnectDevelop'];
			$fonts[] = ['class' => 'fa-dashcube','title' => 'DashCube'];
			$fonts[] = ['class' => 'fa-forumbee','title' => 'ForumBee'];
			$fonts[] = ['class' => 'fa-leanpub','title' => 'LeanPub'];
			$fonts[] = ['class' => 'fa-sellsy','title' => 'Sellsy'];
			$fonts[] = ['class' => 'fa-shirtsinbulk','title' => 'ShirtsInBulk'];
			$fonts[] = ['class' => 'fa-simplybuilt','title' => 'SimplyBuilt'];
			$fonts[] = ['class' => 'fa-skyatlas','title' => 'SkyAtlas'];
			$fonts[] = ['class' => 'fa-cart-plus','title' => 'Cart Plus'];
			$fonts[] = ['class' => 'fa-cart-arrow-down','title' => 'Cart Arrow Down'];
			$fonts[] = ['class' => 'fa-diamond','title' => 'Diamond'];
			$fonts[] = ['class' => 'fa-ship','title' => 'Ship'];
			$fonts[] = ['class' => 'fa-user-secret','title' => 'User Secret'];
			$fonts[] = ['class' => 'fa-motorcycle','title' => 'Motorcycle'];
			$fonts[] = ['class' => 'fa-street-view','title' => 'Street View'];
			$fonts[] = ['class' => 'fa-heartbeat','title' => 'Heartbeat'];
			$fonts[] = ['class' => 'fa-venus','title' => 'Venus'];
			$fonts[] = ['class' => 'fa-mars','title' => 'Mars'];
			$fonts[] = ['class' => 'fa-mercury','title' => 'Mercury'];
			$fonts[] = ['class' => 'fa-intersex','title' => 'Intersex'];
			$fonts[] = ['class' => 'fa-transgender','title' => 'Transgender'];
			$fonts[] = ['class' => 'fa-transgender-alt','title' => 'Transgender Alt'];
			$fonts[] = ['class' => 'fa-venus-double','title' => 'Venus Double'];
			$fonts[] = ['class' => 'fa-mars-double','title' => 'Mars Double'];
			$fonts[] = ['class' => 'fa-venus-mars','title' => 'Venus Mars'];
			$fonts[] = ['class' => 'fa-mars-stroke','title' => 'Mars Stroke'];
			$fonts[] = ['class' => 'fa-mars-stroke-v','title' => 'Mars Stroke V'];
			$fonts[] = ['class' => 'fa-mars-stroke-h','title' => 'Mars Stroke H'];
			$fonts[] = ['class' => 'fa-neuter','title' => 'Neuter'];
			$fonts[] = ['class' => 'fa-genderless','title' => 'Genderless'];
			$fonts[] = ['class' => 'fa-facebook-official','title' => 'Facebook Official'];
			$fonts[] = ['class' => 'fa-pinterest-p','title' => 'Pinterest P'];
			$fonts[] = ['class' => 'fa-whatsapp','title' => 'WhatsApp'];
			$fonts[] = ['class' => 'fa-server','title' => 'Server'];
			$fonts[] = ['class' => 'fa-user-plus','title' => 'User Plus'];
			$fonts[] = ['class' => 'fa-user-times','title' => 'User Times'];
			$fonts[] = ['class' => 'fa-hotel','title' => 'Hotel'];
			$fonts[] = ['class' => 'fa-bed','title' => 'Bed'];
			$fonts[] = ['class' => 'fa-viacoin','title' => 'ViaCoin'];
			$fonts[] = ['class' => 'fa-train','title' => 'Train'];
			$fonts[] = ['class' => 'fa-subway','title' => 'Subway'];
			$fonts[] = ['class' => 'fa-medium','title' => 'Medium'];
			$fonts[] = ['class' => 'fa-yc','title' => 'Yc'];
			$fonts[] = ['class' => 'fa-y-combinator','title' => 'Y Combinator'];
			$fonts[] = ['class' => 'fa-optin-monster','title' => 'Optin Monster'];
			$fonts[] = ['class' => 'fa-opencart','title' => 'Opencart'];
			$fonts[] = ['class' => 'fa-expeditedssl','title' => 'Expedited SSL'];
			$fonts[] = ['class' => 'fa-battery-4','title' => 'Battery 4'];
			$fonts[] = ['class' => 'fa-battery-full','title' => 'Battery Full'];
			$fonts[] = ['class' => 'fa-battery-3','title' => 'Battery 3'];
			$fonts[] = ['class' => 'fa-battery-three-quarters','title' => 'Battery Three Quarters'];
			$fonts[] = ['class' => 'fa-battery-2','title' => 'Battery 2'];
			$fonts[] = ['class' => 'fa-battery-half','title' => 'Battery Half'];
			$fonts[] = ['class' => 'fa-battery-1','title' => 'Battery 1'];
			$fonts[] = ['class' => 'fa-battery-quarter','title' => 'Battery Quarter'];
			$fonts[] = ['class' => 'fa-battery-0','title' => 'Battery 0'];
			$fonts[] = ['class' => 'fa-battery-empty','title' => 'Battery Empty'];
			$fonts[] = ['class' => 'fa-mouse-pointer','title' => 'Mouse Pointer'];
			$fonts[] = ['class' => 'fa-i-cursor','title' => 'I Cursor'];
			$fonts[] = ['class' => 'fa-object-group','title' => 'Object Group'];
			$fonts[] = ['class' => 'fa-object-ungroup','title' => 'Object Ungroup'];
			$fonts[] = ['class' => 'fa-sticky-note','title' => 'Sticky Note'];
			$fonts[] = ['class' => 'fa-sticky-note-o','title' => 'Sticky Note O'];
			$fonts[] = ['class' => 'fa-cc-jcb','title' => 'CC JCB'];
			$fonts[] = ['class' => 'fa-cc-diners-club','title' => 'CC Diners Club'];
			$fonts[] = ['class' => 'fa-clone','title' => 'Clone'];
			$fonts[] = ['class' => 'fa-balance-scale','title' => 'Balance Scale'];
			$fonts[] = ['class' => 'fa-hourglass-o','title' => 'Hourglass O'];
			$fonts[] = ['class' => 'fa-hourglass-1','title' => 'Hourglass 1'];
			$fonts[] = ['class' => 'fa-hourglass-start','title' => 'Hourglass Start'];
			$fonts[] = ['class' => 'fa-hourglass-2','title' => 'Hourglass 2'];
			$fonts[] = ['class' => 'fa-hourglass-half','title' => 'Hourglass Half'];
			$fonts[] = ['class' => 'fa-hourglass-3','title' => 'Hourglass 3'];
			$fonts[] = ['class' => 'fa-hourglass-end','title' => 'Hourglass End'];
			$fonts[] = ['class' => 'fa-hourglass','title' => 'Hourglass'];
			$fonts[] = ['class' => 'fa-hand-grab-o','title' => 'Hand Grab O'];
			$fonts[] = ['class' => 'fa-hand-rock-o','title' => 'Hand Rock O'];
			$fonts[] = ['class' => 'fa-hand-stop-o','title' => 'Hand Stop O'];
			$fonts[] = ['class' => 'fa-hand-paper-o','title' => 'Hand Paper O'];
			$fonts[] = ['class' => 'fa-hand-scissors-o','title' => 'Hand Scissors O'];
			$fonts[] = ['class' => 'fa-hand-lizard-o','title' => 'Hand Lizard O'];
			$fonts[] = ['class' => 'fa-hand-spock-o','title' => 'Hand Spock O'];
			$fonts[] = ['class' => 'fa-hand-pointer-o','title' => 'Hand Pointer O'];
			$fonts[] = ['class' => 'fa-hand-peace-o','title' => 'Hand Peace O'];
			$fonts[] = ['class' => 'fa-trademark','title' => 'Trademark'];
			$fonts[] = ['class' => 'fa-registered','title' => 'Registered'];
			$fonts[] = ['class' => 'fa-creative-commons','title' => 'Creative Commons'];
			$fonts[] = ['class' => 'fa-gg','title' => 'Gg'];
			$fonts[] = ['class' => 'fa-gg-circle','title' => 'Gg Circle'];
			$fonts[] = ['class' => 'fa-tripadvisor','title' => 'TripAdvisor'];
			$fonts[] = ['class' => 'fa-odnoklassniki','title' => 'Odnoklassniki'];
			$fonts[] = ['class' => 'fa-odnoklassniki-square','title' => 'Odnoklassniki Square'];
			$fonts[] = ['class' => 'fa-get-pocket','title' => 'Get Pocket'];
			$fonts[] = ['class' => 'fa-wikipedia-w','title' => 'Wikipedia W'];
			$fonts[] = ['class' => 'fa-safari','title' => 'Safari'];
			$fonts[] = ['class' => 'fa-chrome','title' => 'Chrome'];
			$fonts[] = ['class' => 'fa-firefox','title' => 'Firefox'];
			$fonts[] = ['class' => 'fa-opera','title' => 'Opera'];
			$fonts[] = ['class' => 'fa-internet-explorer','title' => 'Internet Explorer'];
			$fonts[] = ['class' => 'fa-tv','title' => 'Tv'];
			$fonts[] = ['class' => 'fa-television','title' => 'Television'];
			$fonts[] = ['class' => 'fa-contao','title' => 'Contao'];
			$fonts[] = ['class' => 'fa-500px','title' => '500px'];
			$fonts[] = ['class' => 'fa-amazon','title' => 'Amazon'];
			$fonts[] = ['class' => 'fa-calendar-plus-o','title' => 'Calendar Plus O'];
			$fonts[] = ['class' => 'fa-calendar-minus-o','title' => 'Calendar Minus O'];
			$fonts[] = ['class' => 'fa-calendar-times-o','title' => 'Calendar Times O'];
			$fonts[] = ['class' => 'fa-calendar-check-o','title' => 'Calendar Check O'];
			$fonts[] = ['class' => 'fa-industry','title' => 'Industry'];
			$fonts[] = ['class' => 'fa-map-pin','title' => 'Map Pin'];
			$fonts[] = ['class' => 'fa-map-signs','title' => 'Map Signs'];
			$fonts[] = ['class' => 'fa-map-o','title' => 'Map O'];
			$fonts[] = ['class' => 'fa-map','title' => 'Map'];
			$fonts[] = ['class' => 'fa-commenting','title' => 'Commenting'];
			$fonts[] = ['class' => 'fa-commenting-o','title' => 'Commenting O'];
			$fonts[] = ['class' => 'fa-houzz','title' => 'Houzz'];
			$fonts[] = ['class' => 'fa-vimeo','title' => 'Vimeo'];
			$fonts[] = ['class' => 'fa-black-tie','title' => 'Black Tie'];
			$fonts[] = ['class' => 'fa-fonticons','title' => 'FontIcons'];
			$fonts[] = ['class' => 'fa-reddit-alien','title' => 'Reddit Alien'];
			$fonts[] = ['class' => 'fa-edge','title' => 'Edge'];
			$fonts[] = ['class' => 'fa-credit-card-alt','title' => 'Credit Card Alt'];
			$fonts[] = ['class' => 'fa-codiepie','title' => 'Codiepie'];
			$fonts[] = ['class' => 'fa-modx','title' => 'ModX'];
			$fonts[] = ['class' => 'fa-fort-awesome','title' => 'Fort Awesome'];
			$fonts[] = ['class' => 'fa-usb','title' => 'Usb'];
			$fonts[] = ['class' => 'fa-product-hunt','title' => 'Product Hunt'];
			$fonts[] = ['class' => 'fa-mixcloud','title' => 'MixCloud'];
			$fonts[] = ['class' => 'fa-scribd','title' => 'Scribd'];
			$fonts[] = ['class' => 'fa-pause-circle','title' => 'Pause Circle'];
			$fonts[] = ['class' => 'fa-pause-circle-o','title' => 'Pause Circle O'];
			$fonts[] = ['class' => 'fa-stop-circle','title' => 'Stop Circle'];
			$fonts[] = ['class' => 'fa-stop-circle-o','title' => 'Stop Circle O'];
			$fonts[] = ['class' => 'fa-shopping-bag','title' => 'Shopping Bag'];
			$fonts[] = ['class' => 'fa-shopping-basket','title' => 'Shopping Basket'];
			$fonts[] = ['class' => 'fa-hashtag','title' => 'Hashtag'];
			$fonts[] = ['class' => 'fa-bluetooth','title' => 'Bluetooth'];
			$fonts[] = ['class' => 'fa-bluetooth-b','title' => 'Bluetooth B'];
			$fonts[] = ['class' => 'fa-percent','title' => 'Percent'];
			$fonts[] = ['class' => 'fa-gitlab','title' => 'Gitlab'];
			$fonts[] = ['class' => 'fa-wpbeginner','title' => 'WpBeginner'];
			$fonts[] = ['class' => 'fa-wpforms','title' => 'WpForms'];
			$fonts[] = ['class' => 'fa-envira','title' => 'Envira'];
			$fonts[] = ['class' => 'fa-universal-access','title' => 'Universal Access'];
			$fonts[] = ['class' => 'fa-wheelchair-alt','title' => 'Wheelchair Alt'];
			$fonts[] = ['class' => 'fa-question-circle-o','title' => 'Question Circle O'];
			$fonts[] = ['class' => 'fa-blind','title' => 'Blind'];
			$fonts[] = ['class' => 'fa-audio-description','title' => 'Audio Description'];
			$fonts[] = ['class' => 'fa-volume-control-phone','title' => 'Volume Control Phone'];
			$fonts[] = ['class' => 'fa-braille','title' => 'Braille'];
			$fonts[] = ['class' => 'fa-assistive-listening-systems','title' => 'Assistive Listening Systems'];
			$fonts[] = ['class' => 'fa-asl-interpreting','title' => 'Asl Interpreting'];
			$fonts[] = ['class' => 'fa-american-sign-language-interpreting','title' => 'American Sign Language Interpreting'];
			$fonts[] = ['class' => 'fa-deafness','title' => 'Deafness'];
			$fonts[] = ['class' => 'fa-hard-of-hearing','title' => 'Hard of Hearing'];
			$fonts[] = ['class' => 'fa-deaf','title' => 'Deaf'];
			$fonts[] = ['class' => 'fa-glide','title' => 'Glide'];
			$fonts[] = ['class' => 'fa-glide-g','title' => 'Glide G'];
			$fonts[] = ['class' => 'fa-signing','title' => 'Signing'];
			$fonts[] = ['class' => 'fa-sign-language','title' => 'Sign Language'];
			$fonts[] = ['class' => 'fa-low-vision','title' => 'Low Vision'];
			$fonts[] = ['class' => 'fa-viadeo','title' => 'Viadeo'];
			$fonts[] = ['class' => 'fa-viadeo-square','title' => 'Viadeo Square'];
			$fonts[] = ['class' => 'fa-snapchat','title' => 'SnapChat'];
			$fonts[] = ['class' => 'fa-snapchat-ghost','title' => 'SnapChat Ghost'];
			$fonts[] = ['class' => 'fa-snapchat-square','title' => 'SnapChat Square'];
			$fonts[] = ['class' => 'fa-pied-piper','title' => 'Pied Piper'];
			$fonts[] = ['class' => 'fa-first-order','title' => 'First Order'];
			$fonts[] = ['class' => 'fa-yoast','title' => 'Yoast'];
			$fonts[] = ['class' => 'fa-themeisle','title' => 'Theme Isle'];
			$fonts[] = ['class' => 'fa-google-plus-circle','title' => 'Google Plus Circle'];
			$fonts[] = ['class' => 'fa-google-plus-official','title' => 'Google Plus Official'];
			$fonts[] = ['class' => 'fa-fa','title' => 'Fa'];
			$fonts[] = ['class' => 'fa-font-awesome','title' => 'Font Awesome'];
			$fonts[] = ['class' => 'fa-handshake-o','title' => 'Handshake O'];
			$fonts[] = ['class' => 'fa-envelope-open','title' => 'Envelope Open'];
			$fonts[] = ['class' => 'fa-envelope-open-o','title' => 'Envelope Open O'];
			$fonts[] = ['class' => 'fa-linode','title' => 'Linode'];
			$fonts[] = ['class' => 'fa-address-book','title' => 'Address Book'];
			$fonts[] = ['class' => 'fa-address-book-o','title' => 'Address Book O'];
			$fonts[] = ['class' => 'fa-vcard','title' => 'Vcard'];
			$fonts[] = ['class' => 'fa-address-card','title' => 'Address Card'];
			$fonts[] = ['class' => 'fa-vcard-o','title' => 'Vcard O'];
			$fonts[] = ['class' => 'fa-address-card-o','title' => 'Address Card O'];
			$fonts[] = ['class' => 'fa-user-circle','title' => 'User Circle'];
			$fonts[] = ['class' => 'fa-user-circle-o','title' => 'User Circle O'];
			$fonts[] = ['class' => 'fa-user-o','title' => 'User O'];
			$fonts[] = ['class' => 'fa-id-badge','title' => 'Id Badge'];
			$fonts[] = ['class' => 'fa-drivers-license','title' => 'Drivers License'];
			$fonts[] = ['class' => 'fa-id-card','title' => 'Id Card'];
			$fonts[] = ['class' => 'fa-drivers-license-o','title' => 'Drivers License O'];
			$fonts[] = ['class' => 'fa-id-card-o','title' => 'Id Card O'];
			$fonts[] = ['class' => 'fa-quora','title' => 'Quora'];
			$fonts[] = ['class' => 'fa-free-code-camp','title' => 'Free Code Camp'];
			$fonts[] = ['class' => 'fa-telegram','title' => 'Telegram'];
			$fonts[] = ['class' => 'fa-thermometer-4','title' => 'Thermometer 4'];
			$fonts[] = ['class' => 'fa-thermometer','title' => 'Thermometer'];
			$fonts[] = ['class' => 'fa-thermometer-full','title' => 'Thermometer Full'];
			$fonts[] = ['class' => 'fa-thermometer-3','title' => 'Thermometer 3'];
			$fonts[] = ['class' => 'fa-thermometer-three-quarters','title' => 'Thermometer Three Quarters'];
			$fonts[] = ['class' => 'fa-thermometer-2','title' => 'Thermometer 2'];
			$fonts[] = ['class' => 'fa-thermometer-half','title' => 'Thermometer Half'];
			$fonts[] = ['class' => 'fa-thermometer-1','title' => 'Thermometer 1'];
			$fonts[] = ['class' => 'fa-thermometer-quarter','title' => 'Thermometer Quarter'];
			$fonts[] = ['class' => 'fa-thermometer-0','title' => 'Thermometer 0'];
			$fonts[] = ['class' => 'fa-thermometer-empty','title' => 'Thermometer Empty'];
			$fonts[] = ['class' => 'fa-shower','title' => 'Shower'];
			$fonts[] = ['class' => 'fa-bathtub','title' => 'Bathtub'];
			$fonts[] = ['class' => 'fa-s15','title' => 'S15'];
			$fonts[] = ['class' => 'fa-bath','title' => 'Bath'];
			$fonts[] = ['class' => 'fa-podcast','title' => 'Podcast'];
			$fonts[] = ['class' => 'fa-window-maximize','title' => 'Window Maximize'];
			$fonts[] = ['class' => 'fa-window-minimize','title' => 'Window Minimize'];
			$fonts[] = ['class' => 'fa-window-restore','title' => 'Window Restore'];
			$fonts[] = ['class' => 'fa-times-rectangle','title' => 'Times Rectangle'];
			$fonts[] = ['class' => 'fa-window-close','title' => 'Window Close'];
			$fonts[] = ['class' => 'fa-times-rectangle-o','title' => 'Times Rectangle O'];
			$fonts[] = ['class' => 'fa-window-close-o','title' => 'Window Close O'];
			$fonts[] = ['class' => 'fa-bandcamp','title' => 'Bandcamp'];
			$fonts[] = ['class' => 'fa-grav','title' => 'Grav'];
			$fonts[] = ['class' => 'fa-etsy','title' => 'Etsy'];
			$fonts[] = ['class' => 'fa-imdb','title' => 'Imdb'];
			$fonts[] = ['class' => 'fa-ravelry','title' => 'Ravelry'];
			$fonts[] = ['class' => 'fa-eercast','title' => 'Eercast'];
			$fonts[] = ['class' => 'fa-microchip','title' => 'Microchip'];
			$fonts[] = ['class' => 'fa-snowflake-o','title' => 'Snowflake O'];
			$fonts[] = ['class' => 'fa-superpowers','title' => 'Superpowers'];
			$fonts[] = ['class' => 'fa-wpexplorer','title' => 'Wpexplorer'];
			$fonts[] = ['class' => 'fa-meetup','title' => 'Meetup'];

			sort($fonts);

			$this->cache->set('fonts', $fonts);
		}

		return $fonts;
	}
}
