/*
 Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","az",{euro:"Avropa valyuta isar?si",lsquo:"Sol t?k dirnaq isar?si",rsquo:"Sag t?k dirnaq isar?si",ldquo:"Sol cüt dirnaq isar?si",rdquo:"Sag cüt dirnaq isar?si",ndash:"Çixma isar?si",mdash:"Tire",iexcl:"Çevrilmis nida isar?si",cent:"Sent isar?si",pound:"Funt sterlinq isar?si",curren:"Valyuta isar?si",yen:"Iena isar?si",brvbar:"Sinmis zolaq",sect:"Paraqraf isar?si",uml:"Umlyaut",copy:"Mü?llif hüquqlari haqqinda isar?si",ordf:"Qadin sira indikatoru (a)",laquo:"Sola göst?r?n cüt bucaqli dirnaq",
not:"QEYRI isar?si",reg:"Qeyd olunmus isar?si",macr:"Makron",deg:"D?r?c? isar?si",sup2:"Yuxari indeks 2",sup3:"Yuxari indeks 3",acute:"Vurgu isar?si",micro:"Mikro isar?si",para:"Abzas isar?si",middot:"Orta nöqt?",cedil:"Tsedilla isar?si",sup1:"Yuxari indeks 1",ordm:"Kisi say indikatoru (o)",raquo:"Saga göst?r?n cüt bucaqli dirnaq",frac14:"Dördd? bir hiss? k?sri",frac12:"Bir yarim k?sri",frac34:"Dördd? üç hiss? k?sri",iquest:"Çevrilmis sual isar?si",Agrave:"Soldan vurgu il? A",Aacute:"Vurgu il? A",
Acirc:"Dam isar?si il? A",Atilde:"Tilda isar?si il? A",Auml:"Umlyaut il? A",Aring:"Dair?li A",AElig:"Æ h?rfi",Ccedil:"Tsedilla il? C",Egrave:"Soldan vurgu il? E",Eacute:"Vurgu il? E",Ecirc:"Dam isar?si il? E",Euml:"Umlyaut il? E",Igrave:"Soldan vurgu il? I",Iacute:"Vurgu il? I",Icirc:"Dam isar?si il? I",Iuml:"Umlyaut il? I",ETH:"Eth latin h?rfi",Ntilde:"Tilda isar?si il? N",Ograve:"Soldan vurgu il? O",Oacute:"Vurgu il? O",Ocirc:"Dam isar?si il? E",Otilde:"Tilda isar?si il? O",Ouml:"Umlyaut il? O",
times:"Vurma isar?si",Oslash:"Üstx?ttli O",Ugrave:"Soldan vurgu il? U",Uacute:"Vurgu il? U",Ucirc:"Dam isar?si il? U",Uuml:"Umlyaut il? U",Yacute:"Vurgu il? Y",THORN:"Thorn h?rfi",szlig:"Iti s kiçik h?rfi",agrave:"Soldan vurgu il? a",aacute:"Vurgu il? a",acirc:"Dam isar?si il? a",atilde:"Tilda isar?si il? a",auml:"Umlyaut il? a",aring:"Dair?li a",aelig:"æ h?rfi",ccedil:"ç h?rfi",egrave:"Soldan vurgu il? e",eacute:"Vurgu il? e",ecirc:"Dam isar?si il? e",euml:"Umlyaut il? e",igrave:"Soldan vurgu il? i",
iacute:"Vurgu il? i",icirc:"Dam isar?si il? i",iuml:"Umlyaut il? i",eth:"eth kiçik h?rfi",ntilde:"Tilda isar?si il? n",ograve:"Soldan vurgu il? o",oacute:"Vurgu il? o",ocirc:"Dam isar?si il? o",otilde:"Tilda isar?si il? o",ouml:"Umlyaut il? o",divide:"Bölünm? isar?si",oslash:"Üstx?ttli o",ugrave:"Soldan vurgu il? u",uacute:"Vurgu il? u",ucirc:"Dam isar?si il? u",uuml:"Umlyaut il? u",yacute:"Vurgu il? y",thorn:"Thorn kiçik h?rfi",yuml:"Umlyaut il? y",OElig:"OE ligaturasi",oelig:"oe ligaturasi",372:"Dam isar?si il? W",
374:"Dam isar?si il? Y",373:"Dam isar?si il? w",375:"Dam isar?si il? y",sbquo:"Asagi dirnaq",8219:"T?k yuxari çevrilmis dirnaq",bdquo:"Asagi cütlü dirnaqlar",hellip:"Üfüqi ellips",trade:"?mt?? nisani",9658:"Saga göst?rici",bull:"Marker",rarr:"Saga istiqam?tl?ndir?n ox",rArr:"Saga istiqam?tl?ndir?n cütlü ox",hArr:"H?rt?r?fli ox",diams:"Qara k?rpic",asymp:"T?xmini barab?r"});
