/*
 Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","cs",{euro:"Znak eura",lsquo:"Pocátecní uvozovka jednoduchá",rsquo:"Koncová uvozovka jednoduchá",ldquo:"Pocátecní uvozovka dvojitá",rdquo:"Koncová uvozovka dvojitá",ndash:"En pomlcka",mdash:"Em pomlcka",iexcl:"Obrácený vykricník",cent:"Znak centu",pound:"Znak libry",curren:"Znak meny",yen:"Znak jenu",brvbar:"Prerušená svislá cára",sect:"Znak oddílu",uml:"Prehláska",copy:"Znak copyrightu",ordf:"Ženský indikátor rodu",laquo:"Znak dvojitých lomených uvozovek vlevo",
not:"Logistický zápor",reg:"Znak registrace",macr:"Pomlcka nad",deg:"Znak stupne",sup2:"Dvojka jako horní index",sup3:"Trojka jako horní index",acute:"Cárka nad vpravo",micro:"Znak mikro",para:"Znak odstavce",middot:"Tecka uprostred",cedil:"Ocásek vlevo",sup1:"Jednicka jako horní index",ordm:"Mužský indikátor rodu",raquo:"Znak dvojitých lomených uvozovek vpravo",frac14:"Obycejný zlomek jedna ctvrtina",frac12:"Obycejný zlomek jedna polovina",frac34:"Obycejný zlomek tri ctvrtiny",iquest:"Znak obráceného otazníku",
Agrave:"Velké písmeno latinky A s cárkou nad vlevo",Aacute:"Velké písmeno latinky A s cárkou nad vpravo",Acirc:"Velké písmeno latinky A s vokánem",Atilde:"Velké písmeno latinky A s tildou",Auml:"Velké písmeno latinky A s dvema teckami",Aring:"Velké písmeno latinky A s kroužkem nad",AElig:"Velké písmeno latinky Æ",Ccedil:"Velké písmeno latinky C s ocáskem vlevo",Egrave:"Velké písmeno latinky E s cárkou nad vlevo",Eacute:"Velké písmeno latinky E s cárkou nad vpravo",Ecirc:"Velké písmeno latinky E s vokánem",
Euml:"Velké písmeno latinky E s dvema teckami",Igrave:"Velké písmeno latinky I s cárkou nad vlevo",Iacute:"Velké písmeno latinky I s cárkou nad vpravo",Icirc:"Velké písmeno latinky I s vokánem",Iuml:"Velké písmeno latinky I s dvema teckami",ETH:"Velké písmeno latinky Eth",Ntilde:"Velké písmeno latinky N s tildou",Ograve:"Velké písmeno latinky O s cárkou nad vlevo",Oacute:"Velké písmeno latinky O s cárkou nad vpravo",Ocirc:"Velké písmeno latinky O s vokánem",Otilde:"Velké písmeno latinky O s tildou",
Ouml:"Velké písmeno latinky O s dvema teckami",times:"Znak násobení",Oslash:"Velké písmeno latinky O preškrtnuté",Ugrave:"Velké písmeno latinky U s cárkou nad vlevo",Uacute:"Velké písmeno latinky U s cárkou nad vpravo",Ucirc:"Velké písmeno latinky U s vokánem",Uuml:"Velké písmeno latinky U s dvema teckami",Yacute:"Velké písmeno latinky Y s cárkou nad vpravo",THORN:"Velké písmeno latinky Thorn",szlig:"Malé písmeno latinky ostré s",agrave:"Malé písmeno latinky a s cárkou nad vlevo",aacute:"Malé písmeno latinky a s cárkou nad vpravo",
acirc:"Malé písmeno latinky a s vokánem",atilde:"Malé písmeno latinky a s tildou",auml:"Malé písmeno latinky a s dvema teckami",aring:"Malé písmeno latinky a s kroužkem nad",aelig:"Malé písmeno latinky ae",ccedil:"Malé písmeno latinky c s ocáskem vlevo",egrave:"Malé písmeno latinky e s cárkou nad vlevo",eacute:"Malé písmeno latinky e s cárkou nad vpravo",ecirc:"Malé písmeno latinky e s vokánem",euml:"Malé písmeno latinky e s dvema teckami",igrave:"Malé písmeno latinky i s cárkou nad vlevo",iacute:"Malé písmeno latinky i s cárkou nad vpravo",
icirc:"Malé písmeno latinky i s vokánem",iuml:"Malé písmeno latinky i s dvema teckami",eth:"Malé písmeno latinky eth",ntilde:"Malé písmeno latinky n s tildou",ograve:"Malé písmeno latinky o s cárkou nad vlevo",oacute:"Malé písmeno latinky o s cárkou nad vpravo",ocirc:"Malé písmeno latinky o s vokánem",otilde:"Malé písmeno latinky o s tildou",ouml:"Malé písmeno latinky o s dvema teckami",divide:"Znak delení",oslash:"Malé písmeno latinky o preškrtnuté",ugrave:"Malé písmeno latinky u s cárkou nad vlevo",
uacute:"Malé písmeno latinky u s cárkou nad vpravo",ucirc:"Malé písmeno latinky u s vokánem",uuml:"Malé písmeno latinky u s dvema teckami",yacute:"Malé písmeno latinky y s cárkou nad vpravo",thorn:"Malé písmeno latinky thorn",yuml:"Malé písmeno latinky y s dvema teckami",OElig:"Velká ligatura latinky OE",oelig:"Malá ligatura latinky OE",372:"Velké písmeno latinky W s vokánem",374:"Velké písmeno latinky Y s vokánem",373:"Malé písmeno latinky w s vokánem",375:"Malé písmeno latinky y s vokánem",sbquo:"Dolní 9 uvozovka jednoduchá",
8219:"Horní obrácená 9 uvozovka jednoduchá",bdquo:"Dolní 9 uvozovka dvojitá",hellip:"Trojteckový úvod",trade:"Obchodní znacka",9658:"Cerný ukazatel smerující vpravo",bull:"Kolecko",rarr:"Šipka vpravo",rArr:"Dvojitá šipka vpravo",hArr:"Dvojitá šipka vlevo a vpravo",diams:"Cerné piky",asymp:"Témer se rovná"});
