/*
 Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","eo",{euro:"Eurosigno",lsquo:"Supra 6-citilo",rsquo:"Supra 9-citilo",ldquo:"Supra 66-citilo",rdquo:"Supra 99-citilo",ndash:"Streketo",mdash:"Substreko",iexcl:"Renversita krisigno",cent:"Cendosigno",pound:"Pundosigno",curren:"Monersigno",yen:"Enosigno",brvbar:"Rompita vertikala streko",sect:"Kurba paragrafo",uml:"Tremao",copy:"Kopirajtosigno",ordf:"Adjektiva numerfinajo",laquo:"Duobla malplio-citilo",not:"Negohoko",reg:"Registrita marko",macr:"Superstreko",deg:"Gradosigno",
sup2:"Supra indico 2",sup3:"Supra indico 3",acute:"Dekstra korno",micro:"Mikrosigno",para:"Rekta paragrafo",middot:"Meza punkto",cedil:"Zoeto",sup1:"Supra indico 1",ordm:"Substantiva numerfinajo",raquo:"Duobla plio-citilo",frac14:"Kvaronosigno",frac12:"Duonosigno",frac34:"Trikvaronosigno",iquest:"renversita demandosigno",Agrave:"Latina ceflitero A kun liva korno",Aacute:"Latina ceflitero A kun dekstra korno",Acirc:"Latina ceflitero A kun capelo",Atilde:"Latina ceflitero A kun tildo",Auml:"Latina ceflitero A kun tremao",
Aring:"Latina ceflitero A kun superringo",AElig:"Latina ceflitera ligaturo Æ",Ccedil:"Latina ceflitero C kun zoeto",Egrave:"Latina ceflitero E kun liva korno",Eacute:"Latina ceflitero E kun dekstra korno",Ecirc:"Latina ceflitero E kun capelo",Euml:"Latina ceflitero E kun tremao",Igrave:"Latina ceflitero I kun liva korno",Iacute:"Latina ceflitero I kun dekstra korno",Icirc:"Latina ceflitero I kun capelo",Iuml:"Latina ceflitero I kun tremao",ETH:"Latina ceflitero islanda edo",Ntilde:"Latina ceflitero N kun tildo",
Ograve:"Latina ceflitero O kun liva korno",Oacute:"Latina ceflitero O kun dekstra korno",Ocirc:"Latina ceflitero O kun capelo",Otilde:"Latina ceflitero O kun tildo",Ouml:"Latina ceflitero O kun tremao",times:"Multipliko",Oslash:"Latina ceflitero O trastrekita",Ugrave:"Latina ceflitero U kun liva korno",Uacute:"Latina ceflitero U kun dekstra korno",Ucirc:"Latina ceflitero U kun capelo",Uuml:"Latina ceflitero U kun tremao",Yacute:"Latina ceflitero Y kun dekstra korno",THORN:"Latina ceflitero islanda dorno",
szlig:"Latina etlitero germana sozo (akra s)",agrave:"Latina etlitero a kun liva korno",aacute:"Latina etlitero a kun dekstra korno",acirc:"Latina etlitero a kun capelo",atilde:"Latina etlitero a kun tildo",auml:"Latina etlitero a kun tremao",aring:"Latina etlitero a kun superringo",aelig:"Latina etlitera ligaturo æ",ccedil:"Latina etlitero c kun zoeto",egrave:"Latina etlitero e kun liva korno",eacute:"Latina etlitero e kun dekstra korno",ecirc:"Latina etlitero e kun capelo",euml:"Latina etlitero e kun tremao",
igrave:"Latina etlitero i kun liva korno",iacute:"Latina etlitero i kun dekstra korno",icirc:"Latina etlitero i kun capelo",iuml:"Latina etlitero i kun tremao",eth:"Latina etlitero islanda edo",ntilde:"Latina etlitero n kun tildo",ograve:"Latina etlitero o kun liva korno",oacute:"Latina etlitero o kun dekstra korno",ocirc:"Latina etlitero o kun capelo",otilde:"Latina etlitero o kun tildo",ouml:"Latina etlitero o kun tremao",divide:"Dividosigno",oslash:"Latina etlitero o trastrekita",ugrave:"Latina etlitero u kun liva korno",
uacute:"Latina etlitero u kun dekstra korno",ucirc:"Latina etlitero u kun capelo",uuml:"Latina etlitero u kun tremao",yacute:"Latina etlitero y kun dekstra korno",thorn:"Latina etlitero islanda dorno",yuml:"Latina etlitero y kun tremao",OElig:"Latina ceflitera ligaturo Œ",oelig:"Latina etlitera ligaturo œ",372:"Latina ceflitero W kun capelo",374:"Latina ceflitero Y kun capelo",373:"Latina etlitero w kun capelo",375:"Latina etlitero y kun capelo",sbquo:"Suba 9-citilo",8219:"Supra renversita 9-citilo",
bdquo:"Suba 99-citilo",hellip:"Tripunkto",trade:"Varmarka signo",9658:"Nigra sago dekstren",bull:"Bulmarko",rarr:"Sago dekstren",rArr:"Duobla sago dekstren",hArr:"Duobla sago maldekstren",diams:"Nigra kvadrato",asymp:"Preskau egala"});
