/*
 Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","hr",{euro:"Euro znak",lsquo:"Lijevi jednostruki navodnik",rsquo:"Desni jednostruki navodnik",ldquo:"Lijevi dvostruki navodnik",rdquo:"Desni dvostruki navodnik",ndash:"En crtica",mdash:"Em crtica",iexcl:"Naopaki usklicnik",cent:"Cent znak",pound:"Funta znak",curren:"Znak valute",yen:"Yen znak",brvbar:"Potrgana precka",sect:"Znak odjeljka",uml:"Prijeglasi",copy:"Copyright znak",ordf:"Ženska redna oznaka",laquo:"Lijevi dvostruki uglati navodnik",not:"Not znak",
reg:"Registered znak",macr:"Crta iznad",deg:"Stupanj znak",sup2:"Eksponent 2",sup3:"Eksponent tri",acute:"Akcent",micro:"Mikro znak",para:"Znak paragrafa",middot:"Srednja tocka",cedil:"Cedilla",sup1:"Eksponent 1",ordm:"Muška redna oznaka",raquo:"Desni dvostruku uglati navodnik",frac14:"Cetvrtina",frac12:"Polovina",frac34:"Tri cetvrtine",iquest:"Naopaki upitnik",Agrave:"Veliko latinsko slovo A s akcentom",Aacute:"Latinicno veliko slovo A sa oštrim naglaskom",Acirc:"Latinicno veliko slovo A sa circumflex",
Atilde:"Latinicno veliko slovo A sa tildom",Auml:"Latinicno veliko slovo A sa diaeresis",Aring:"Latinicno veliko slovo A sa gornjim prstenom",AElig:"Latinicno veliko slovo Æ",Ccedil:"Veliko latinicno slovo C sa cedilla",Egrave:"Veliko latinicno slovo E sa akcentom",Eacute:"Veliko latinicno slovo E sa  akcentom",Ecirc:"Veliko latinicno slovo E sa circumflex",Euml:"Veliko latinicno slovo E sa diaresis",Igrave:"Veliko latinicno slovo I sa akcentom",Iacute:"Veliko latinicno slovo I sa akcentom",Icirc:"Veliko latinicno slovo I sa circumflex",
Iuml:"Veliko latinicno slovo I sa diaresis",ETH:"Veliko latinicno slovo Eth",Ntilde:"Veliko latinicno slovo N sa tildom",Ograve:"Veliko latinicno slovo O sa akcentom",Oacute:"Veliko latinicno slovo O sa akcentom",Ocirc:"Veliko latinicno slovo O sa circumflex",Otilde:"Veliko latinicno slovo O sa tildom",Ouml:"Veliko latinicno slovo O sa diaresis",times:"Znak množenja",Oslash:"Veliko latinicno slovo O sa crtom",Ugrave:"Veliko latinicno slovo U sa akcentom",Uacute:"Veliko latinicno slovo U sa akcentom",
Ucirc:"Veliko latinicno slovo U sa circumflex",Uuml:"Veliko latinicno slovo U sa diaresis",Yacute:"Veliko latinicno slovo Y sa akcentom",THORN:"Veliko latinicno slovo Trn",szlig:"Malo latinicno slovo oštro s",agrave:"Malo latinicno slovo a sa akcentom",aacute:"Malo latinicno slovo sa akcentom",acirc:"Malo latinicno slovo a sa circumflex",atilde:"Malo latinicno slovo a sa tildom",auml:"Malo latinicno slovo a sa diaresis",aring:"Malo latinicno slovo a sa gornjim prstenom",aelig:"Malo latinicno slovo æ",
ccedil:"Malo latinicno slovo e sa cedilla",egrave:"Malo latinicno slovo e sa akcentom",eacute:"Malo latinicno slovo e sa akcentom",ecirc:"Malo latinicno slovo e sa circumflex",euml:"Malo latinicno slovo e sa diaresis",igrave:"Malo latinicno slovo i sa akcentom",iacute:"Malo latinicno slovo i sa akcentom",icirc:"Malo latinicno slovo i sa circumflex",iuml:"Malo latinicno slovo i sa diaresis",eth:"Malo latinicno slovo eth",ntilde:"Malo latinicno slovo n sa tildom",ograve:"Malo latinicno slovo o sa akcentom",
oacute:"Malo latinicno slovo o sa akcentom",ocirc:"Malo latinicno slovo o sa circumflex",otilde:"Malo latinicno slovo o sa tildom",ouml:"Malo latinicno slovo o sa diaresis",divide:"Znak dijeljenja",oslash:"Malo latinicno slovo o sa crtom",ugrave:"Malo latinicno slovo s akcentom",uacute:"Malo latinicno slovo u sa akcentom",ucirc:"Malo latinicno slovo sa circumflex",uuml:"Malo latinicno slovo u sa diaresis",yacute:"Malo latinicno slovo y s akcentom",thorn:"Malo latinicno slovo Trn",yuml:"Malo latinicno slovo y sa diaresis",
OElig:"Veliko latinicno slovo OE",oelig:"Malo latinicno slovoe OE",372:"Veliko latinicno slovo W sa circumflex",374:"Veliko latinicno slovo Y sa circumflex",373:"Malo latinicno slovo w sa circumflex",375:"Malo latinicno slovo y sa circumflex",sbquo:"Jednostruki donji navodnik",8219:"Jednostruki gornji navodnik",bdquo:"Dvostruki donji navodnik",hellip:"Tri tockice",trade:"TM znak",9658:"Crni desni pokazivac",bull:"Bullet",rarr:"Desna strelica",rArr:"Desna dvostruka strelica",hArr:"Dvostruka strelica",
diams:"Crni dijamant",asymp:"Približno"});
