/*
 Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","lv",{euro:"Euro zime",lsquo:"Kreisa  vienkartiga pedina",rsquo:"Laba  vienkartiga pedina",ldquo:"Kreisa  dubult pedina",rdquo:"Laba dubult pedina",ndash:"En svitra",mdash:"Em svitra",iexcl:"Apgriezta izsaukuma zime",cent:"Centu naudas zime",pound:"Sterlinu marcinu naudas zime",curren:"Valutas zime",yen:"Jenu naudas zime",brvbar:"Vertikala parrauta linija",sect:"Paragrafa zime",uml:"Diakritiska zime",copy:"Autortiesibu zime",ordf:"Sieviškas kartas raditajs",
laquo:"Kreisa dubult stura pedinu zime",not:"Neparakstits",reg:"Registreta zime",macr:"Garumzime",deg:"Gradu zime",sup2:"Augšraksts divi",sup3:"Augšraksts tris",acute:"Akuta uzsvara zime",micro:"Mikro zime",para:"Rindkopas zime ",middot:"Videjs punkts",cedil:"Akitis zem burta",sup1:"Augšraksts viens",ordm:"Viriškigas kartas raditajs",raquo:"Laba dubult stura pedinu zime",frac14:"Vulgara frakcija 1/4",frac12:"Vulgara frakcija 1/2",frac34:"Vulgara frakcija 3/4",iquest:"Apgriezta jautajuma zime",Agrave:"Lielais latinu burts A ar uzsvara zimi",
Aacute:"Lielais  latinu burts A ar akutu uzsvara zimi",Acirc:"Lielais latinu burts A ar diakritisku zimi",Atilde:"Lielais latinu burts A ar tildi ",Auml:"Lielais latinu burts A ar diakritisko zimi",Aring:"Lielais latinu burts A ar apliti augša",AElig:"Lielais latinu burts Æ",Ccedil:"Lielais latinu burts C ar akiti zem burta",Egrave:"Lielais latinu burts E ar apostrofu",Eacute:"Lielais latinu burts E ar akutu uzsvara zimi",Ecirc:"Lielais latinu burts E ar diakritisko zimi",Euml:"Lielais latinu burts E ar diakritisko zimi",
Igrave:"Lielais latinu burts I ar uzsvaras  zimi",Iacute:"Lielais latinu burts I ar akutu uzsvara zimi",Icirc:"Lielais latinu burts I ar diakritisko zimi",Iuml:"Lielais latinu burts I ar diakritisko zimi",ETH:"Lielais latinu burts Eth",Ntilde:"Lielais latinu burts N ar tildi",Ograve:"Lielais latinu burts O ar uzsvara zimi",Oacute:"Lielais latinu burts O ar akuto uzsvara zimi",Ocirc:"Lielais latinu burts O ar diakritisko zimi",Otilde:"Lielais latinu burts O ar tildi",Ouml:"Lielais latinu burts O ar diakritisko zimi",
times:"Reizinašanas zime ",Oslash:"Lielais latinu burts O ar iesvitrojumu",Ugrave:"Lielais latinu burts U ar uzsvaras zimi",Uacute:"Lielais latinu burts U ar akuto uzsvars zimi",Ucirc:"Lielais latinu burts U ar diakritisko zimi",Uuml:"Lielais latinu burts U ar diakritisko zimi",Yacute:"Lielais latinu burts Y ar akuto uzsvaras zimi",THORN:"Lielais latinu burts torn",szlig:"Mazs latinu burts ar ligaturu",agrave:"Mazs latinu burts a ar uzsvara zimi",aacute:"Mazs latinu burts a ar akuto uzsvara zimi",
acirc:"Mazs latinu burts a ar diakritisko zimi",atilde:"Mazs latinu burts a ar tildi",auml:"Mazs latinu burts a ar diakritisko zimi",aring:"Mazs latinu burts a ar apliti augša",aelig:"Mazs latinu burts æ",ccedil:"Mazs latinu burts c ar akiti zem burta",egrave:"Mazs latinu burts e ar uzsvara zimi ",eacute:"Mazs latinu burts e ar akutu uzsvara zimi",ecirc:"Mazs latinu burts e ar diakritisko zimi",euml:"Mazs latinu burts e ar diakritisko zimi",igrave:"Mazs latinu burts i ar uzsvara zimi ",iacute:"Mazs latinu burts i ar akutu uzsvara zimi",
icirc:"Mazs latinu burts i ar diakritisko zimi",iuml:"Mazs latinu burts i ar diakritisko zimi",eth:"Mazs latinu burts eth",ntilde:"Mazs latinu burts n ar tildi",ograve:"Mazs latinu burts o ar uzsvara zimi ",oacute:"Mazs latinu burts o ar akutu uzsvara zimi",ocirc:"Mazs latinu burts o ar diakritisko zimi",otilde:"Mazs latinu burts o ar tildi",ouml:"Mazs latinu burts o ar diakritisko zimi",divide:"Dališanas zime",oslash:"Mazs latinu burts o ar iesvitrojumu",ugrave:"Mazs latinu burts u ar uzsvara zimi ",
uacute:"Mazs latinu burts u ar  akutu uzsvara zimi",ucirc:"Mazs latinu burts u ar diakritisko zimi",uuml:"Mazs latinu burts u ar diakritisko zimi",yacute:"Mazs latinu burts y ar  akutu uzsvaras zimi",thorn:"Mazs latinu burts torns",yuml:"Mazs latinu burts y ar diakritisko zimi",OElig:"Liela latinu ligatura OE",oelig:"Maza latinu ligatura oe",372:"Liels latinu burts W ar diakritisko zimi ",374:"Liels latinu burts Y ar diakritisko zimi ",373:"Mazs latinu burts w ar diakritisko zimi ",375:"Mazs latinu burts y ar diakritisko zimi ",
sbquo:"Mazas-9 vienkartigas pedinas",8219:"Lielas-9 vienkartigas apgrieztas pedinas",bdquo:"Mazas-9 dubultas pedinas",hellip:"Horizontali daudzpunkti",trade:"Precu zimes zime",9658:"Melns pa labi pagriezts raditajs",bull:"Lode",rarr:"Bulta pa labi",rArr:"Dubulta Bulta pa labi",hArr:"Bulta pa kreisi",diams:"Dubulta Bulta pa kreisi",asymp:"Gandriz vienads ar"});
