/*
 Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","pl",{euro:"Znak euro",lsquo:"Cudzyslów pojedynczy otwierajacy",rsquo:"Cudzyslów pojedynczy zamykajacy",ldquo:"Cudzyslów apostrofowy otwierajacy",rdquo:"Cudzyslów apostrofowy zamykajacy",ndash:"Pólpauza",mdash:"Pauza",iexcl:"Odwrócony wykrzyknik",cent:"Znak centa",pound:"Znak funta",curren:"Znak waluty",yen:"Znak jena",brvbar:"Przerwana pionowa kreska",sect:"Paragraf",uml:"Diereza",copy:"Znak praw autorskich",ordf:"Wskaznik rodzaju zenskiego liczebnika porzadkowego",
laquo:"Lewy cudzyslów ostrokatny",not:"Znak negacji",reg:"Zastrzezony znak towarowy",macr:"Makron",deg:"Znak stopnia",sup2:"Druga potega",sup3:"Trzecia potega",acute:"Akcent ostry",micro:"Znak mikro",para:"Znak akapitu",middot:"Kropka srodkowa",cedil:"Cedylla",sup1:"Pierwsza potega",ordm:"Wskaznik rodzaju meskiego liczebnika porzadkowego",raquo:"Prawy cudzyslów ostrokatny",frac14:"Ulamek zwykly jedna czwarta",frac12:"Ulamek zwykly jedna druga",frac34:"Ulamek zwykly trzy czwarte",iquest:"Odwrócony znak zapytania",
Agrave:"Wielka litera A z akcentem ciezkim",Aacute:"Wielka litera A z akcentem ostrym",Acirc:"Wielka litera A z akcentem przeciaglym",Atilde:"Wielka litera A z tylda",Auml:"Wielka litera A z diereza",Aring:"Wielka litera A z kólkiem",AElig:"Wielka ligatura Æ",Ccedil:"Wielka litera C z cedylla",Egrave:"Wielka litera E z akcentem ciezkim",Eacute:"Wielka litera E z akcentem ostrym",Ecirc:"Wielka litera E z akcentem przeciaglym",Euml:"Wielka litera E z diereza",Igrave:"Wielka litera I z akcentem ciezkim",
Iacute:"Wielka litera I z akcentem ostrym",Icirc:"Wielka litera I z akcentem przeciaglym",Iuml:"Wielka litera I z diereza",ETH:"Wielka litera Eth",Ntilde:"Wielka litera N z tylda",Ograve:"Wielka litera O z akcentem ciezkim",Oacute:"Wielka litera O z akcentem ostrym",Ocirc:"Wielka litera O z akcentem przeciaglym",Otilde:"Wielka litera O z tylda",Ouml:"Wielka litera O z diereza",times:"Znak mnozenia wektorowego",Oslash:"Wielka litera O z przekresleniem",Ugrave:"Wielka litera U z akcentem ciezkim",Uacute:"Wielka litera U z akcentem ostrym",
Ucirc:"Wielka litera U z akcentem przeciaglym",Uuml:"Wielka litera U z diereza",Yacute:"Wielka litera Y z akcentem ostrym",THORN:"Wielka litera Thorn",szlig:"Mala litera ostre s (eszet)",agrave:"Mala litera a z akcentem ciezkim",aacute:"Mala litera a z akcentem ostrym",acirc:"Mala litera a z akcentem przeciaglym",atilde:"Mala litera a z tylda",auml:"Mala litera a z diereza",aring:"Mala litera a z kólkiem",aelig:"Mala ligatura æ",ccedil:"Mala litera c z cedylla",egrave:"Mala litera e z akcentem ciezkim",
eacute:"Mala litera e z akcentem ostrym",ecirc:"Mala litera e z akcentem przeciaglym",euml:"Mala litera e z diereza",igrave:"Mala litera i z akcentem ciezkim",iacute:"Mala litera i z akcentem ostrym",icirc:"Mala litera i z akcentem przeciaglym",iuml:"Mala litera i z diereza",eth:"Mala litera eth",ntilde:"Mala litera n z tylda",ograve:"Mala litera o z akcentem ciezkim",oacute:"Mala litera o z akcentem ostrym",ocirc:"Mala litera o z akcentem przeciaglym",otilde:"Mala litera o z tylda",ouml:"Mala litera o z diereza",
divide:"Anglosaski znak dzielenia",oslash:"Mala litera o z przekresleniem",ugrave:"Mala litera u z akcentem ciezkim",uacute:"Mala litera u z akcentem ostrym",ucirc:"Mala litera u z akcentem przeciaglym",uuml:"Mala litera u z diereza",yacute:"Mala litera y z akcentem ostrym",thorn:"Mala litera thorn",yuml:"Mala litera y z diereza",OElig:"Wielka ligatura OE",oelig:"Mala ligatura oe",372:"Wielka litera W z akcentem przeciaglym",374:"Wielka litera Y z akcentem przeciaglym",373:"Mala litera w z akcentem przeciaglym",
375:"Mala litera y z akcentem przeciaglym",sbquo:"Pojedynczy apostrof dolny",8219:"Pojedynczy apostrof górny",bdquo:"Podwójny apostrof dolny",hellip:"Wielokropek",trade:"Znak towarowy",9658:"Czarny wskaznik wskazujacy w prawo",bull:"Punktor",rarr:"Strzalka w prawo",rArr:"Podwójna strzalka w prawo",hArr:"Podwójna strzalka obustronna",diams:"Czarny znak karo",asymp:"Znak prawie równe"});
