/*
 Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","sk",{euro:"Znak eura",lsquo:"Lavá jednoduchá úvodzovka",rsquo:"Pravá jednoduchá úvodzovka",ldquo:"Pravá dvojitá úvodzovka",rdquo:"Pravá dvojitá úvodzovka",ndash:"En pomlcka",mdash:"Em pomlcka",iexcl:"Obrátený výkricník",cent:"Znak centu",pound:"Znak libry",curren:"Znak meny",yen:"Znak jenu",brvbar:"Prerušená zvislá ciara",sect:"Znak odseku",uml:"Prehláska",copy:"Znak copyrightu",ordf:"Ženský indikátor rodu",laquo:"Znak dvojitých lomených úvodzoviek vlavo",not:"Logistický zápor",
reg:"Znak registrácie",macr:"Pomlcka nad",deg:"Znak stupna",sup2:"Dvojka ako horný index",sup3:"Trojka ako horný index",acute:"Dlžen",micro:"Znak mikro",para:"Znak odstavca",middot:"Bodka uprostred",cedil:"Chvost vlavo",sup1:"Jednotka ako horný index",ordm:"Mužský indikátor rodu",raquo:"Znak dvojitých lomených úvodzoviek vpravo",frac14:"Obycajný zlomok jedna štvrtina",frac12:"Obycajný zlomok jedna polovica",frac34:"Obycajný zlomok tri štvrtiny",iquest:"Otocený otáznik",Agrave:"Velké písmeno latinky A s accentom",
Aacute:"Velké písmeno latinky A s dlžnom",Acirc:"Velké písmeno latinky A s mäkcenom",Atilde:"Velké písmeno latinky A s tildou",Auml:"Velké písmeno latinky A s dvoma bodkami",Aring:"Velké písmeno latinky A s krúžkom nad",AElig:"Velké písmeno latinky Æ",Ccedil:"Velké písmeno latinky C s chvostom vlavo",Egrave:"Velké písmeno latinky E s accentom",Eacute:"Velké písmeno latinky E s dlžnom",Ecirc:"Velké písmeno latinky E s mäkcenom",Euml:"Velké písmeno latinky E s dvoma bodkami",Igrave:"Velké písmeno latinky I s accentom",
Iacute:"Velké písmeno latinky I s dlžnom",Icirc:"Velké písmeno latinky I s mäkcenom",Iuml:"Velké písmeno latinky I s dvoma bodkami",ETH:"Velké písmeno latinky Eth",Ntilde:"Velké písmeno latinky N s tildou",Ograve:"Velké písmeno latinky O s accentom",Oacute:"Velké písmeno latinky O s dlžnom",Ocirc:"Velké písmeno latinky O s mäkcenom",Otilde:"Velké písmeno latinky O s tildou",Ouml:"Velké písmeno latinky O s dvoma bodkami",times:"Znak násobenia",Oslash:"Velké písmeno latinky O preškrtnuté",Ugrave:"Velké písmeno latinky U s accentom",
Uacute:"Velké písmeno latinky U s dlžnom",Ucirc:"Velké písmeno latinky U s mäkcenom",Uuml:"Velké písmeno latinky U s dvoma bodkami",Yacute:"Velké písmeno latinky Y s dlžnom",THORN:"Velké písmeno latinky Thorn",szlig:"Malé písmeno latinky ostré s",agrave:"Malé písmeno latinky a s accentom",aacute:"Malé písmeno latinky a s dlžnom",acirc:"Malé písmeno latinky a s mäkcenom",atilde:"Malé písmeno latinky a s tildou",auml:"Malé písmeno latinky a s dvoma bodkami",aring:"Malé písmeno latinky a s krúžkom nad",
aelig:"Malé písmeno latinky æ",ccedil:"Malé písmeno latinky c s chvostom vlavo",egrave:"Malé písmeno latinky e s accentom",eacute:"Malé písmeno latinky e s dlžnom",ecirc:"Malé písmeno latinky e s mäkcenom",euml:"Malé písmeno latinky e s dvoma bodkami",igrave:"Malé písmeno latinky i s accentom",iacute:"Malé písmeno latinky i s dlžnom",icirc:"Malé písmeno latinky i s mäkcenom",iuml:"Malé písmeno latinky i s dvoma bodkami",eth:"Malé písmeno latinky eth",ntilde:"Malé písmeno latinky n s tildou",ograve:"Malé písmeno latinky o s accentom",
oacute:"Malé písmeno latinky o s dlžnom",ocirc:"Malé písmeno latinky o s mäkcenom",otilde:"Malé písmeno latinky o s tildou",ouml:"Malé písmeno latinky o s dvoma bodkami",divide:"Znak delenia",oslash:"Malé písmeno latinky o preškrtnuté",ugrave:"Malé písmeno latinky u s accentom",uacute:"Malé písmeno latinky u s dlžnom",ucirc:"Malé písmeno latinky u s mäkcenom",uuml:"Malé písmeno latinky u s dvoma bodkami",yacute:"Malé písmeno latinky y s dlžnom",thorn:"Malé písmeno latinky thorn",yuml:"Malé písmeno latinky y s dvoma bodkami",
OElig:"Velká ligatúra latinky OE",oelig:"Malá ligatúra latinky OE",372:"Velké písmeno latinky W s mäkcenom",374:"Velké písmeno latinky Y s mäkcenom",373:"Malé písmeno latinky w s mäkcenom",375:"Malé písmeno latinky y s mäkcenom",sbquo:"Dolná jednoduchá 9-úvodzovka",8219:"Horná jednoduchá otocená 9-úvodzovka",bdquo:"Dolná dvojitá 9-úvodzovka",hellip:"Trojbodkový úvod",trade:"Znak ibchodnej znacky",9658:"Cierny ukazovatel smerujúci vpravo",bull:"Kruh",rarr:"Šípka vpravo",rArr:"Dvojitá šipka vpravo",
hArr:"Dvojitá šipka vlavo a vpravo",diams:"Cierne piky",asymp:"Skoro sa rovná"});
