/*
 Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","sl",{euro:"Znak za evro",lsquo:"Levi enojni narekovaj",rsquo:"Desni enojni narekovaj",ldquo:"Levi dvojni narekovaj",rdquo:"Desni dvojni narekovaj",ndash:"Pomišljaj",mdash:"Dolgi pomišljaj",iexcl:"Obrnjen klicaj",cent:"Znak za cent",pound:"Znak za funt",curren:"Znak valute",yen:"Znak za jen",brvbar:"Zlomljena crta",sect:"Znak za clen",uml:"Diereza",copy:"Znak avtorskih pravic",ordf:"Ženski zaporedni kazalnik",laquo:"Levi dvojni lomljeni narekovaj",not:"Znak za ne",
reg:"Registrirani znak",macr:"Nadcrtano",deg:"Znak za stopinje",sup2:"Nadpisano dva",sup3:"Nadpisano tri",acute:"Ostrivec",micro:"Znak za mikro",para:"Znak za odstavek",middot:"Usredinjena pika",cedil:"Cedilla",sup1:"Nadpisano ena",ordm:"Moški zaporedni kazalnik",raquo:"Desno obrnjen dvojni kotni narekovaj",frac14:"Ena cetrtina",frac12:"Ena polovica",frac34:"Tri cetrtine",iquest:"Obrnjen vprašaj",Agrave:"Velika latinska crka A s krativcem",Aacute:"Velika latinska crka A z ostrivcem",Acirc:"Velika latinska crka A s strešico",
Atilde:"Velika latinska crka A z tildo",Auml:"Velika latinska crka A z diaeresis-om",Aring:"Velika latinska crka A z obrocem",AElig:"Velika latinska crka Æ",Ccedil:"Velika latinska crka C s cedillo",Egrave:"Velika latinska crka E s krativcem",Eacute:"Velika latinska crka E z ostrivcem",Ecirc:"Velika latinska crka E s strešico",Euml:"Velika latinska crka E z diaeresis-om",Igrave:"Velika latinska crka I s krativcem",Iacute:"Velika latinska crka I z ostrivcem",Icirc:"Velika latinska crka I s strešico",
Iuml:"Velika latinska crka I z diaeresis-om",ETH:"Velika latinska crka Eth",Ntilde:"Velika latinska crka N s tildo",Ograve:"Velika latinska crka O s krativcem",Oacute:"Velika latinska crka O z ostrivcem",Ocirc:"Velika latinska crka O s strešico",Otilde:"Velika latinska crka O s tildo",Ouml:"Velika latinska crka O z diaeresis-om",times:"Znak za množenje",Oslash:"Velika precrtana latinska crka O",Ugrave:"Velika latinska crka U s krativcem",Uacute:"Velika latinska crka U z ostrivcem",Ucirc:"Velika latinska crka U s strešico",
Uuml:"Velika latinska crka U z diaeresis-om",Yacute:"Velika latinska crka Y z ostrivcem",THORN:"Velika latinska crka Thorn",szlig:"Mala ostra latinska crka s",agrave:"Mala latinska crka a s krativcem",aacute:"Mala latinska crka a z ostrivcem",acirc:"Mala latinska crka a s strešico",atilde:"Mala latinska crka a s tildo",auml:"Mala latinska crka a z diaeresis-om",aring:"Mala latinska crka a z obrocem",aelig:"Mala latinska crka æ",ccedil:"Mala latinska crka c s cedillo",egrave:"Mala latinska crka e s krativcem",
eacute:"Mala latinska crka e z ostrivcem",ecirc:"Mala latinska crka e s strešico",euml:"Mala latinska crka e z diaeresis-om",igrave:"Mala latinska crka i s krativcem",iacute:"Mala latinska crka i z ostrivcem",icirc:"Mala latinska crka i s strešico",iuml:"Mala latinska crka i z diaeresis-om",eth:"Mala latinska crka eth",ntilde:"Mala latinska crka n s tildo",ograve:"Mala latinska crka o s krativcem",oacute:"Mala latinska crka o z ostrivcem",ocirc:"Mala latinska crka o s strešico",otilde:"Mala latinska crka o s tildo",
ouml:"Mala latinska crka o z diaeresis-om",divide:"Znak za deljenje",oslash:"Mala precrtana latinska crka o",ugrave:"Mala latinska crka u s krativcem",uacute:"Mala latinska crka u z ostrivcem",ucirc:"Mala latinska crka u s strešico",uuml:"Mala latinska crka u z diaeresis-om",yacute:"Mala latinska crka y z ostrivcem",thorn:"Mala latinska crka thorn",yuml:"Mala latinska crka y z diaeresis-om",OElig:"Velika latinska ligatura OE",oelig:"Mala latinska ligatura oe",372:"Velika latinska crka W s strešico",
374:"Velika latinska crka Y s strešico",373:"Mala latinska crka w s strešico",375:"Mala latinska crka y s strešico",sbquo:"Enojni nizki-9 narekovaj",8219:"Enojni visoki-obrnjen-9 narekovaj",bdquo:"Dvojni nizki-9 narekovaj",hellip:"Horizontalni izpust",trade:"Znak blagovne znamke",9658:"Crni desno-usmerjen kazalec",bull:"Krogla",rarr:"Desno-usmerjena pušcica",rArr:"Desno-usmerjena dvojna pušcica",hArr:"Leva in desna dvojna pušcica",diams:"Crna kara",asymp:"Skoraj enako"});
