/*
 Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","sr-latn",{euro:"Znak eura",lsquo:"Levi simpli znak navoda",rsquo:"Desni simpli znak navoda",ldquo:"Levi dupli znak navoda",rdquo:"Desni dupli znak navoda",ndash:"Kratka crtica",mdash:"Dugacka crtica",iexcl:"Obrnuti uzvicnik",cent:"Znak za cent",pound:"Znak za funt?",curren:"Znak za valutu",yen:"Znak za jen?",brvbar:"Traka sa prekidom",sect:"Znak paragrafa",uml:"Umlaut",copy:"Znak za autorsko pravo",ordf:"Ženski redni indikator",laquo:"Dupla strelica levo",not:"Bez znaka",
reg:"Registrovani znak",macr:"Znak dužine",deg:"Znak za stepen",sup2:"Znak za kvadrat",sup3:"Znak za kub",acute:"Oštar akcenat",micro:"Znak mikro",para:"Znak pasusa",middot:"Srednja tacka",cedil:"Cedila",sup1:"Znak na prvom",ordm:"Muški redni indikator",raquo:"Dupla strelica desno",frac14:"Znak za cetvrtinu",frac12:"Znak za polovinu",frac34:"Znak za trecinu",iquest:"Obrnuti upitnik",Agrave:"Veliko latinicno slovo A sa  obrnutom kukicom.",Aacute:"Veliko latinicno slovo A sa kukicom.",Acirc:"Veliko latinicno slovo A sa savijenom kukicom.",
Atilde:"Veliko latinicno slovo A sa znakom talasa.",Auml:"Veliko latinicno slovo A sa dvotackom",Aring:"Veliko latinicno slovo A sa prstenom iznad.",AElig:"Veliko latinicno slovo Æ",Ccedil:"Veliko latinicno slovo C sa cedilom",Egrave:"Veliko latinicno slovo E sa obrnutom kukicom",Eacute:"Veliko latinicno slovo E sa kukicom.",Ecirc:"Veliko latinicno slovo E sa savijenom kukicom.",Euml:"Veliko latinicno slovo E sa dvotackom",Igrave:"Veliko latinicno slovo I sa obrnutom kukicom",Iacute:"Veliko latinicno slovo I sa kukicom.",
Icirc:"Veliko latinicno slovo I sa savijenom kukicom.",Iuml:"Veliko latinicno slovo I sa dvotackom",ETH:"Veliko latinicno slovo Eth",Ntilde:"Veliko latinicno slovo N sa znakom talasa.",Ograve:"Veliko latinicno slovo O sa obrnutom kukicom",Oacute:"Veliko latinicno slovo O sa kukicom.",Ocirc:"Veliko latinicno slovo O sa savijenom kukicom.",Otilde:"Veliko latinicno slovo O sa znakom talasa.",Ouml:"Veliko latinicno slovo O sa dvotackom",times:"Znak množenja",Oslash:"Latinicno slovo O precrtano",Ugrave:"Veliko latinicno slovo U sa obrnutom kukicom",
Uacute:"Veliko latinicno slovo U sa kukicom",Ucirc:"Veliko latinicno slovo U sa savijenom kukicom.",Uuml:"Veliko latinicno slovo U sa dvotackom",Yacute:"Veliko latinicno slovo Y sa kukicom",THORN:"Veliko latinicno slovo Thotn",szlig:"Malo latinicno slovo s",agrave:"Malo latinicno slovo a sa obrnutom kukicom",aacute:"Malo latinicno slovo a sa kukicom",acirc:"Malo latinicno slovo a sa savijenom kukicom",atilde:"Malo latinicno slovo a sa znakom talasa",auml:"Malo latinicno slovo a sa dvotackom",aring:"Malo latinicno slovo a sa prstenom iznad",
aelig:"Malo latinicno slovo æ",ccedil:"Malo latinicno slovo c sa cedilom",egrave:"Malo latinicno slovo e sa obrnutom kukicom",eacute:"Malo latinicno slovo e sa kukicom",ecirc:"Malo latinicno slovo e sa savijenom kukicom",euml:"Malo latinicno slovo e sa dvotackom",igrave:"Malo latinicno slovo i sa obrnutom kukicom",iacute:"Malo latinicno slovo i sa kukicom",icirc:"Malo latinicno slovo i sa savijenom kukicom",iuml:"Malo latinicno slovo i sa dvotackom",eth:"Malo latinicno slovo eth",ntilde:"Malo latinicno slovo n sa znakom talasa",
ograve:"Malo latinicno slovo o sa obrnutom kukicom",oacute:"Malo latinicno slovo o sa kukicom",ocirc:"Malo latinicno slovo o sa savijenom kukicom",otilde:"Malo latinicno slovo o sa znakom talasa",ouml:"Malo latinicno slovo o dvotackom",divide:"Znak deljenja",oslash:"Malo latinicno slovo o precrtano",ugrave:"Malo latinicno slovo u sa obrnutom kukicom",uacute:"Malo latinicno slovo u sa kukicom",ucirc:"Malo latinicno slovo u sa savijenom kukicom",uuml:"Malo latinicno slovo u sa dvotackom",yacute:"Malo latinicno slovo y sa kukicom",
thorn:"Malo latinicno slovo thorn",yuml:"Malo latinicno slovo y sa dvotackom",OElig:"Veliki latinicni znak OE",oelig:"Mali latinicni znak OE",372:"Veliko latinicno slovo W sa savijenom kukicom.",374:"Veliko latinicno slovo Y sa savijenom kukicom.",373:"Malo latinicno slovo w sa savijenom kukicom.",375:"Malo latinicno slovo y sa savijenom kukicom.",sbquo:"Tipografski simpli navodnik za otvaranje",8219:"Tipografski simpli navodnik za zatvaranje",bdquo:"Tipografski dupli navodnik ",hellip:"Tri tacke",
trade:"Znak robne marke",9658:"Crni pokazivac desno",bull:"Tacka",rarr:"Strelica desno",rArr:"Dupla strelica desno",hArr:"Levo desno dupla strelica",diams:"Crni dijamant znak",asymp:"Znak skoro jednako"});
