/*
 Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","tr",{euro:"Euro isareti",lsquo:"Sol tek tirnak isareti",rsquo:"Sag tek tirnak isareti",ldquo:"Sol çift tirnak isareti",rdquo:"Sag çift tirnak isareti",ndash:"En tire",mdash:"Em tire",iexcl:"Ters ünlem isareti",cent:"Cent isareti",pound:"Pound isareti",curren:"Para birimi isareti",yen:"Yen isareti",brvbar:"Kirik bar",sect:"Bölüm isareti",uml:"Iki sesli harfin ayrilmasi",copy:"Telif hakki isareti",ordf:"Disil sirali gösterge",laquo:"Sol-isaret çift açi tirnak isareti",
not:"Not isareti",reg:"Kayitli isareti",macr:"Makron",deg:"Derece isareti",sup2:"Ikili üstsimge",sup3:"Üçlü üstsimge",acute:"Aksan isareti",micro:"Mikro isareti",para:"Pilcrow isareti",middot:"Orta nokta",cedil:"Kedilla",sup1:"Üstsimge",ordm:"Eril sirali gösterge",raquo:"Sag isaret çift açi tirnak isareti",frac14:"Bayagi kesrin dörtte biri",frac12:"Bayagi kesrin bir yarim",frac34:"Bayagi kesrin dörtte üç",iquest:"Ters soru isareti",Agrave:"Aksanli latin harfi",Aacute:"Asiri aksaniyla Latin harfi",
Acirc:"Çarpik Latin harfi",Atilde:"Tilde latin harfi",Auml:"Sesli harf ayrilimlii latin harfi",Aring:"Halkali latin büyük A harfi",AElig:"Latin büyük Æ harfi",Ccedil:"Latin büyük C harfi ile kedilla",Egrave:"Aksanli latin büyük E harfi",Eacute:"Asiri vurgulu latin büyük E harfi",Ecirc:"Çarpik latin büyük E harfi",Euml:"Sesli harf ayrilimlii latin büyük E harfi",Igrave:"Aksanli latin büyük I harfi",Iacute:"Asiri aksanli latin büyük I harfi",Icirc:"Çarpik latin büyük I harfi",Iuml:"Sesli harf ayrilimlii latin büyük I harfi",
ETH:"Latin büyük Eth harfi",Ntilde:"Tildeli latin büyük N harfi",Ograve:"Aksanli latin büyük O harfi",Oacute:"Asiri aksanli latin büyük O harfi",Ocirc:"Çarpik latin büyük O harfi",Otilde:"Tildeli latin büyük O harfi",Ouml:"Sesli harf ayrilimli latin büyük O harfi",times:"Çarpma isareti",Oslash:"Vurgulu latin büyük O harfi",Ugrave:"Aksanli latin büyük U harfi",Uacute:"Asiri aksanli latin büyük U harfi",Ucirc:"Çarpik latin büyük U harfi",Uuml:"Sesli harf ayrilimli latin büyük U harfi",Yacute:"Asiri aksanli latin büyük Y harfi",
THORN:"Latin büyük Thorn harfi",szlig:"Latin küçük keskin s harfi",agrave:"Aksanli latin küçük a harfi",aacute:"Asiri aksanli latin küçük a harfi",acirc:"Çarpik latin küçük a harfi",atilde:"Tildeli latin küçük a harfi",auml:"Sesli harf ayrilimli latin küçük a harfi",aring:"Halkali latin küçük a harfi",aelig:"Latin büyük æ harfi",ccedil:"Kedillali latin küçük c harfi",egrave:"Aksanli latin küçük e harfi",eacute:"Asiri aksanli latin küçük e harfi",ecirc:"Çarpik latin küçük e harfi",euml:"Sesli harf ayrilimli latin küçük e harfi",
igrave:"Aksanli latin küçük i harfi",iacute:"Asiri aksanli latin küçük i harfi",icirc:"Çarpik latin küçük i harfi",iuml:"Sesli harf ayrilimli latin küçük i harfi",eth:"Latin küçük eth harfi",ntilde:"Tildeli latin küçük n harfi",ograve:"Aksanli latin küçük o harfi",oacute:"Asiri aksanli latin küçük o harfi",ocirc:"Çarpik latin küçük o harfi",otilde:"Tildeli latin küçük o harfi",ouml:"Sesli harf ayrilimli latin küçük o harfi",divide:"Bölme isareti",oslash:"Vurgulu latin küçük o harfi",ugrave:"Aksanli latin küçük u harfi",
uacute:"Asiri aksanli latin küçük u harfi",ucirc:"Çarpik latin küçük u harfi",uuml:"Sesli harf ayrilimli latin küçük u harfi",yacute:"Asiri aksanli latin küçük y harfi",thorn:"Latin küçük thorn harfi",yuml:"Sesli harf ayrilimli latin küçük y harfi",OElig:"Latin büyük bagli OE harfi",oelig:"Latin küçük bagli oe harfi",372:"Çarpik latin büyük W harfi",374:"Çarpik latin büyük Y harfi",373:"Çarpik latin küçük w harfi",375:"Çarpik latin küçük y harfi",sbquo:"Tek düsük-9 tirnak isareti",8219:"Tek yüksek-ters-9 tirnak isareti",
bdquo:"Çift düsük-9 tirnak isareti",hellip:"Yatay elips",trade:"Marka tescili isareti",9658:"Siyah sag isaret isaretçisi",bull:"Koyu nokta",rarr:"Saga dogru ok",rArr:"Saga dogru çift ok",hArr:"Sol, sag çift ok",diams:"Siyah elmas takimi",asymp:"Hemen hemen esit"});
