/*
 Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("specialchar","vi",{euro:"Ký hi?u Euro",lsquo:"D?u ngo?c don trái",rsquo:"D?u ngo?c don ph?i",ldquo:"D?u ngo?c dôi trái",rdquo:"D?u ngo?c dôi ph?i",ndash:"G?ch ngang ti?ng anh",mdash:"G?ch ngang Em",iexcl:"Chuy?n d?i d?u ch?m than",cent:"Ký t? ti?n M?",pound:"Ký t? ti?n Anh",curren:"Ký t? ti?n t?",yen:"Ký t? ti?n Yên Nh?t",brvbar:"Thanh h?ng",sect:"Ký t? khu v?c",uml:"D?u tách dôi",copy:"Ký t? b?n quy?n",ordf:"Ph?n ch? th? gi?ng cái",laquo:"Ch?n d?u ngo?c dôi trái",not:"Không có ký t?",
reg:"Ký t? dang ký",macr:"D?u nguyên âm dài",deg:"Ký t? d?",sup2:"Ch? tr?i lên trên d?ng 2",sup3:"Ch? tr?i lên trên d?ng 3",acute:"D?u tr?ng âm",micro:"Ký t? micro",para:"Ký t? do?n van",middot:"D?u ch?m tròn",cedil:"D?u móc lu?i",sup1:"Ký t? tr?i lên c?p 1",ordm:"Ký t? bi?u hi?n gi?ng d?c",raquo:"Ch?n d?u ngo?c dôi ph?i",frac14:"T? l? m?t ph?n tu",frac12:"T? l? m?t n?a",frac34:"T? l? ba ph?n tu",iquest:"Chuy?n d?i d?u ch?m h?i",Agrave:"Ký t? la-tinh vi?t hoa A v?i d?u huy?n",Aacute:"Ký t? la-tinh vi?t hoa A v?i d?u s?c",
Acirc:"Ký t? la-tinh vi?t hoa A v?i d?u mu",Atilde:"Ký t? la-tinh vi?t hoa A v?i d?u ngã",Auml:"Ký t? la-tinh vi?t hoa A v?i d?u hai ch?m trên d?u",Aring:"Ký t? la-tinh vi?t hoa A v?i bi?u tu?ng vòng tròn trên d?u",AElig:"Ký t? la-tinh vi?t hoa c?a Æ",Ccedil:"Ký t? la-tinh vi?t hoa C v?i d?u móc bên du?i",Egrave:"Ký t? la-tinh vi?t hoa E v?i d?u huy?n",Eacute:"Ký t? la-tinh vi?t hoa E v?i d?u s?c",Ecirc:"Ký t? la-tinh vi?t hoa E v?i d?u mu",Euml:"Ký t? la-tinh vi?t hoa E v?i d?u hai ch?m trên d?u",
Igrave:"Ký t? la-tinh vi?t hoa I v?i d?u huy?n",Iacute:"Ký t? la-tinh vi?t hoa I v?i d?u s?c",Icirc:"Ký t? la-tinh vi?t hoa I v?i d?u mu",Iuml:"Ký t? la-tinh vi?t hoa I v?i d?u hai ch?m trên d?u",ETH:"Vi?t hoa c?a ký t? Eth",Ntilde:"Ký t? la-tinh vi?t hoa N v?i d?u ngã",Ograve:"Ký t? la-tinh vi?t hoa O v?i d?u huy?n",Oacute:"Ký t? la-tinh vi?t hoa O v?i d?u s?c",Ocirc:"Ký t? la-tinh vi?t hoa O v?i d?u mu",Otilde:"Ký t? la-tinh vi?t hoa O v?i d?u ngã",Ouml:"Ký t? la-tinh vi?t hoa O v?i d?u hai ch?m trên d?u",
times:"Ký t? phép toán nhân",Oslash:"Ký t? la-tinh vi?t hoa A v?i d?u ngã xu?ng",Ugrave:"Ký t? la-tinh vi?t hoa U v?i d?u huy?n",Uacute:"Ký t? la-tinh vi?t hoa U v?i d?u s?c",Ucirc:"Ký t? la-tinh vi?t hoa U v?i d?u mu",Uuml:"Ký t? la-tinh vi?t hoa U v?i d?u hai ch?m trên d?u",Yacute:"Ký t? la-tinh vi?t hoa Y v?i d?u s?c",THORN:"Ph?n vi?t hoa c?a ký t? Thorn",szlig:"Ký t? vi?t nh? la-tinh c?a ch? s",agrave:"Ký t? la-tinh thu?ng v?i d?u huy?n",aacute:"Ký t? la-tinh thu?ng v?i d?u s?c",acirc:"Ký t? la-tinh thu?ng v?i d?u mu",
atilde:"Ký t? la-tinh thu?ng v?i d?u ngã",auml:"Ký t? la-tinh thu?ng v?i d?u hai ch?m trên d?u",aring:"Ký t? la-tinh vi?t thu?ng v?i bi?u tu?ng vòng tròn trên d?u",aelig:"Ký t? la-tinh vi?t thu?ng c?a æ",ccedil:"Ký t? la-tinh vi?t thu?ng c?a c v?i d?u móc bên du?i",egrave:"Ký t? la-tinh vi?t thu?ng e v?i d?u huy?n",eacute:"Ký t? la-tinh vi?t thu?ng e v?i d?u s?c",ecirc:"Ký t? la-tinh vi?t thu?ng e v?i d?u mu",euml:"Ký t? la-tinh vi?t thu?ng e v?i d?u hai ch?m trên d?u",igrave:"Ký t? la-tinh vi?t thu?ng i v?i d?u huy?n",
iacute:"Ký t? la-tinh vi?t thu?ng i v?i d?u s?c",icirc:"Ký t? la-tinh vi?t thu?ng i v?i d?u mu",iuml:"Ký t? la-tinh vi?t thu?ng i v?i d?u hai ch?m trên d?u",eth:"Ký t? la-tinh vi?t thu?ng c?a eth",ntilde:"Ký t? la-tinh vi?t thu?ng n v?i d?u ngã",ograve:"Ký t? la-tinh vi?t thu?ng o v?i d?u huy?n",oacute:"Ký t? la-tinh vi?t thu?ng o v?i d?u s?c",ocirc:"Ký t? la-tinh vi?t thu?ng o v?i d?u mu",otilde:"Ký t? la-tinh vi?t thu?ng o v?i d?u ngã",ouml:"Ký t? la-tinh vi?t thu?ng o v?i d?u hai ch?m trên d?u",
divide:"Ký hi?u phép tính chia",oslash:"Ký t? la-tinh vi?t thu?ng o v?i d?u ngã",ugrave:"Ký t? la-tinh vi?t thu?ng u v?i d?u huy?n",uacute:"Ký t? la-tinh vi?t thu?ng u v?i d?u s?c",ucirc:"Ký t? la-tinh vi?t thu?ng u v?i d?u mu",uuml:"Ký t? la-tinh vi?t thu?ng u v?i d?u hai ch?m trên d?u",yacute:"Ký t? la-tinh vi?t thu?ng y v?i d?u s?c",thorn:"Ký t? la-tinh vi?t thu?ng c?a ch? thorn",yuml:"Ký t? la-tinh vi?t thu?ng y v?i d?u hai ch?m trên d?u",OElig:"Ký t? la-tinh vi?t hoa g?ch n?i OE",oelig:"Ký t? la-tinh vi?t thu?ng g?ch n?i OE",
372:"Ký t? la-tinh vi?t hoa W v?i d?u mu",374:"Ký t? la-tinh vi?t hoa Y v?i d?u mu",373:"Ký t? la-tinh vi?t thu?ng w v?i d?u mu",375:"Ký t? la-tinh vi?t thu?ng y v?i d?u mu",sbquo:"D?u ngo?c don th?p s?-9",8219:"D?u ngo?c don d?o ngu?c s?-9",bdquo:"G?p dôi d?u ngo?c don s?-9",hellip:"Tinh du?c chi?u ngang",trade:"Ký t? thuong hi?u",9658:"Ký t? tr? v? hu?ng bên ph?i màu den",bull:"Ký hi?u",rarr:"Mui tên hu?ng bên ph?i",rArr:"Mui tên hu?ng bên ph?i d?ng dôi",hArr:"Mui tên hu?ng bên trái d?ng dôi",diams:"Ký hi?u hình thoi",
asymp:"G?n b?ng v?i"});
