name: PHPCS

on:
  push:
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run PHPCS (uses phpcs.xml)
        run: ./vendor/bin/phpcs --standard=phpcs.xml
